"use strict";

export const allSets = {
  fdn: { count: 730, name: "Foundations" },
  j25: { count: 779, name: "Foundations Jumpstart" },
  dsk: { count: 417, name: "Duskmourn: House of Horror" },
  blb: { count: 397, name: "Bloomburrow" },
  acr: { count: 309, name: "Assassin's Creed" },
  mh3: { count: 527, name: "Modern Horizons 3" },
  otj: { count: 374, name: "Outlaws of Thunder Junction" },
  pip: { count: 1068, name: "Fallout" },
  clu: { count: 284, name: "Ravnica: Clue Edition" },
  mkm: { count: 450, name: "Murders at Karlov Manor" },
  rvr: { count: 531, name: "Ravnica Remastered" },
  lci: { count: 416, name: "The Lost Caverns of Ixalan" },
  who: { count: 1178, name: "Doctor Who" },
  wot: { count: 103, name: "Wilds of Eldraine: Enchanting Tales" },
  woe: { count: 381, name: "Wilds of Eldraine" },
  cmm: { count: 1067, name: "Commander Masters" },
  ltr: { count: 856, name: "The Lord of the Rings: Tales of Middle-earth" },
  mat: { count: 230, name: "March of the Machine: The Aftermath" },
  mom: { count: 387, name: "March of the Machine" },
  mul: { count: 261, name: "Multiverse Legends" },
  sir: { count: 294, name: "Shadows over Innistrad Remastered" },
  one: { count: 479, name: "Phyrexia: All Will Be One" },
  dmr: { count: 457, name: "Dominaria Remastered" },
  j22: { count: 835, name: "Jumpstart 2022" },
  "30a": { count: 594, name: "30th Anniversary Edition" },
  bro: { count: 399, name: "The Brothers' War" },
  gn3: { count: 135, name: "Game Night: Free-for-All" },
  unf: { count: 639, name: "Unfinity" },
  dmu: { count: 453, name: "Dominaria United" },
  "2x2": { count: 579, name: "Double Masters 2022" },
  hbg: { count: 436, name: "Alchemy Horizons: Baldur's Gate" },
  clb: { count: 936, name: "Commander Legends: Battle for Baldur's Gate" },
  snc: { count: 513, name: "Streets of New Capenna" },
  neo: { count: 531, name: "Kamigawa: Neon Dynasty" },
  dbl: { count: 535, name: "Innistrad: Double Feature" },
  vow: { count: 423, name: "Innistrad: Crimson Vow" },
  mid: { count: 400, name: "Innistrad: Midnight Hunt" },
  j21: { count: 389, name: "Jumpstart: Historic Horizons" },
  afr: { count: 424, name: "Adventures in the Forgotten Realms" },
  mh2: { count: 494, name: "Modern Horizons 2" },
  sta: { count: 126, name: "Strixhaven Mystical Archive" },
  stx: { count: 393, name: "Strixhaven: School of Mages" },
  tsr: { count: 411, name: "Time Spiral Remastered" },
  khm: { count: 426, name: "Kaldheim" },
  cmr: { count: 718, name: "Commander Legends" },
  klr: { count: 302, name: "Kaladesh Remastered" },
  plst: { count: 4809, name: "The List" },
  znr: { count: 408, name: "Zendikar Rising" },
  akr: { count: 339, name: "Amonkhet Remastered" },
  "2xm": { count: 384, name: "Double Masters" },
  jmp: { count: 497, name: "Jumpstart" },
  m21: { count: 397, name: "Core Set 2021" },
  iko: { count: 390, name: "Ikoria: Lair of Behemoths" },
  thb: { count: 358, name: "Theros Beyond Death" },
  sld: { count: 1681, name: "Secret Lair Drop" },
  eld: { count: 399, name: "Throne of Eldraine" },
  m20: { count: 345, name: "Core Set 2020" },
  mh1: { count: 255, name: "Modern Horizons" },
  war: { count: 312, name: "War of the Spark" },
  rna: { count: 273, name: "Ravnica Allegiance" },
  uma: { count: 254, name: "Ultimate Masters" },
  grn: { count: 273, name: "Guilds of Ravnica" },
  m19: { count: 314, name: "Core Set 2019" },
  bbd: { count: 256, name: "Battlebond" },
  dom: { count: 280, name: "Dominaria" },
  a25: { count: 249, name: "Masters 25" },
  rix: { count: 205, name: "Rivals of Ixalan" },
  ust: { count: 268, name: "Unstable" },
  ima: { count: 249, name: "Iconic Masters" },
  xln: { count: 289, name: "Ixalan" },
  hou: { count: 209, name: "Hour of Devastation" },
  akh: { count: 287, name: "Amonkhet" },
  mm3: { count: 249, name: "Modern Masters 2017" },
  aer: { count: 197, name: "Aether Revolt" },
  pz2: { count: 282, name: "Treasure Chest" },
  kld: { count: 278, name: "Kaladesh" },
  cn2: { count: 222, name: "Conspiracy: Take the Crown" },
  emn: { count: 208, name: "Eldritch Moon" },
  ema: { count: 249, name: "Eternal Masters" },
  soi: { count: 302, name: "Shadows over Innistrad" },
  ogw: { count: 187, name: "Oath of the Gatewatch" },
  bfz: { count: 299, name: "Battle for Zendikar" },
  ori: { count: 288, name: "Magic Origins" },
  mm2: { count: 249, name: "Modern Masters 2015" },
  tpr: { count: 269, name: "Tempest Remastered" },
  dtk: { count: 264, name: "Dragons of Tarkir" },
  frf: { count: 191, name: "Fate Reforged" },
  ktk: { count: 293, name: "Khans of Tarkir" },
  m15: { count: 284, name: "Magic 2015" },
  vma: { count: 325, name: "Vintage Masters" },
  cns: { count: 210, name: "Conspiracy" },
  jou: { count: 165, name: "Journey into Nyx" },
  bng: { count: 165, name: "Born of the Gods" },
  ths: { count: 249, name: "Theros" },
  m14: { count: 249, name: "Magic 2014" },
  mma: { count: 229, name: "Modern Masters" },
  dgm: { count: 156, name: "Dragon's Maze" },
  gtc: { count: 249, name: "Gatecrash" },
  rtr: { count: 274, name: "Return to Ravnica" },
  m13: { count: 249, name: "Magic 2013" },
  pc2: { count: 156, name: "Planechase 2012" },
  avr: { count: 244, name: "Avacyn Restored" },
  dka: { count: 158, name: "Dark Ascension" },
  isd: { count: 264, name: "Innistrad" },
  m12: { count: 249, name: "Magic 2012" },
  nph: { count: 175, name: "New Phyrexia" },
  mbs: { count: 155, name: "Mirrodin Besieged" },
  me4: { count: 269, name: "Masters Edition IV" },
  ps11: { count: 224, name: "Salvat 2011" },
  td0: { count: 197, name: "Magic Online Theme Decks" },
  som: { count: 249, name: "Scars of Mirrodin" },
  m11: { count: 249, name: "Magic 2011" },
  dpa: { count: 113, name: "Duels of the Planeswalkers" },
  roe: { count: 248, name: "Rise of the Eldrazi" },
  wwk: { count: 145, name: "Worldwake" },
  zen: { count: 269, name: "Zendikar" },
  me3: { count: 230, name: "Masters Edition III" },
  hop: { count: 169, name: "Planechase" },
  m10: { count: 249, name: "Magic 2010" },
  arb: { count: 145, name: "Alara Reborn" },
  con: { count: 145, name: "Conflux" },
  ala: { count: 250, name: "Shards of Alara" },
  me2: { count: 245, name: "Masters Edition II" },
  eve: { count: 180, name: "Eventide" },
  shm: { count: 302, name: "Shadowmoor" },
  mor: { count: 150, name: "Morningtide" },
  lrw: { count: 301, name: "Lorwyn" },
  me1: { count: 195, name: "Masters Edition" },
  "10e": { count: 510, name: "Tenth Edition" },
  fut: { count: 180, name: "Future Sight" },
  plc: { count: 165, name: "Planar Chaos" },
  tsp: { count: 301, name: "Time Spiral" },
  csp: { count: 155, name: "Coldsnap" },
  dis: { count: 180, name: "Dissension" },
  gpt: { count: 167, name: "Guildpact" },
  rav: { count: 306, name: "Ravnica: City of Guilds" },
  psal: { count: 720, name: "Salvat 2005" },
  "9ed": { count: 709, name: "Ninth Edition" },
  sok: { count: 165, name: "Saviors of Kamigawa" },
  bok: { count: 165, name: "Betrayers of Kamigawa" },
  unh: { count: 168, name: "Unhinged" },
  chk: { count: 307, name: "Champions of Kamigawa" },
  "5dn": { count: 165, name: "Fifth Dawn" },
  dst: { count: 165, name: "Darksteel" },
  mrd: { count: 306, name: "Mirrodin" },
  "8ed": { count: 710, name: "Eighth Edition" },
  scg: { count: 143, name: "Scourge" },
  lgn: { count: 145, name: "Legions" },
  ons: { count: 351, name: "Onslaught" },
  jud: { count: 143, name: "Judgment" },
  tor: { count: 143, name: "Torment" },
  ody: { count: 353, name: "Odyssey" },
  apc: { count: 143, name: "Apocalypse" },
  "7ed": { count: 708, name: "Seventh Edition" },
  pls: { count: 146, name: "Planeshift" },
  inv: { count: 353, name: "Invasion" },
  pcy: { count: 144, name: "Prophecy" },
  nem: { count: 143, name: "Nemesis" },
  mmq: { count: 350, name: "Mercadian Masques" },
  uds: { count: 143, name: "Urza's Destiny" },
  ptk: { count: 180, name: "Portal Three Kingdoms" },
  "6ed": { count: 351, name: "Classic Sixth Edition" },
  ulg: { count: 143, name: "Urza's Legacy" },
  usg: { count: 356, name: "Urza's Saga" },
  p02: { count: 165, name: "Portal Second Age" },
  exo: { count: 143, name: "Exodus" },
  sth: { count: 143, name: "Stronghold" },
  tmp: { count: 350, name: "Tempest" },
  wth: { count: 167, name: "Weatherlight" },
  por: { count: 257, name: "Portal" },
  "5ed": { count: 460, name: "Fifth Edition" },
  vis: { count: 167, name: "Visions" },
  mir: { count: 353, name: "Mirage" },
  all: { count: 199, name: "Alliances" },
  ptc: { count: 308, name: "Pro Tour Collector Set" },
  hml: { count: 140, name: "Homelands" },
  ren: { count: 122, name: "Renaissance" },
  chr: { count: 125, name: "Chronicles" },
  ice: { count: 383, name: "Ice Age" },
  "4ed": { count: 379, name: "Fourth Edition" },
  fem: { count: 187, name: "Fallen Empires" },
  drk: { count: 122, name: "The Dark" },
  sum: { count: 306, name: "Summer Magic / Edgar" },
  leg: { count: 310, name: "Legends" },
  "3ed": { count: 306, name: "Revised Edition" },
  atq: { count: 102, name: "Antiquities" },
  cei: { count: 302, name: "Intl. Collectors' Edition" },
  ced: { count: 302, name: "Collectors' Edition" },
  "2ed": { count: 302, name: "Unlimited Edition" },
  leb: { count: 302, name: "Limited Edition Beta" },
  lea: { count: 295, name: "Limited Edition Alpha" },
};

export const userNames = {
  "152135173813698561": "Ben",
  "135410033524604928": "Yems",
  194831804329492480: "Oli",
  "312274225144791052": "Dan",
  "307938372943478785": "Ollie",
  "203238971009007616": "Tom",
};
