"use strict";

export const allSets = {
  dft: { count: 3, name: "Aetherdrift" },
  inr: { count: 6, name: "Innistrad Remastered" },
  pspl: { count: 1, name: "Spotlight Series" },
  pf25: { count: 1, name: "MagicFest 2025" },
  pio: { count: 23, name: "Pioneer Masters" },
  afdn: { count: 54, name: "Foundations Art Series" },
  ffdn: { count: 2, name: "Foundations Front Cards" },
  pfdn: { count: 81, name: "Foundations Promos" },
  fj25: { count: 46, name: "Foundations Jumpstart Front Cards" },
  tfdn: { count: 33, name: "Foundations Tokens" },
  j25: { count: 779, name: "Foundations Jumpstart" },
  fdc: { count: 3, name: "Foundations Commander" },
  fdn: { count: 730, name: "Foundations" },
  pltc: { count: 4, name: "Tales of Middle-earth Deluxe Commander Kit" },
  ydsk: { count: 30, name: "Alchemy: Duskmourn" },
  pdsk: { count: 160, name: "Duskmourn: House of Horror Promos" },
  dsc: { count: 373, name: "Duskmourn: House of Horror Commander" },
  tdsk: { count: 18, name: "Duskmourn: House of Horror Tokens" },
  adsk: { count: 54, name: "Duskmourn: House of Horror Art Series" },
  tdsc: { count: 23, name: "Duskmourn Commander Tokens" },
  dsk: { count: 418, name: "Duskmourn: House of Horror" },
  yblb: { count: 30, name: "Alchemy: Bloomburrow" },
  plg24: { count: 4, name: "Love Your LGS 2024" },
  ablb: { count: 54, name: "Bloomburrow Art Series" },
  tblc: { count: 41, name: "Bloomburrow Commander Tokens" },
  pblb: { count: 160, name: "Bloomburrow Promos" },
  tblb: { count: 30, name: "Bloomburrow Tokens" },
  mb2: { count: 385, name: "Mystery Booster 2" },
  pcbb: { count: 5, name: "Cowboy Bebop" },
  blb: { count: 398, name: "Bloomburrow" },
  blc: { count: 356, name: "Bloomburrow Commander" },
  macr: { count: 2, name: "Assassin's Creed Minigames" },
  aacr: { count: 20, name: "Assassin's Creed Art Series" },
  acr: { count: 309, name: "Assassin's Creed" },
  tacr: { count: 8, name: "Assassin's Creed Tokens" },
  pmh3: { count: 80, name: "Modern Horizons 3 Promos" },
  smh3: { count: 1, name: "Modern Horizons 3 Substitute Cards" },
  amh3: { count: 54, name: "Modern Horizons 3 Art Series" },
  tmh3: { count: 43, name: "Modern Horizons 3 Tokens" },
  m3c: { count: 398, name: "Modern Horizons 3 Commander" },
  tm3c: { count: 28, name: "Modern Horizons 3 Commander Tokens" },
  mh3: { count: 528, name: "Modern Horizons 3" },
  h2r: { count: 16, name: "Modern Horizons 2 Timeshifts" },
  yotj: { count: 30, name: "Alchemy: Outlaws of Thunder Junction" },
  potj: { count: 160, name: "Outlaws of Thunder Junction Promos" },
  totj: { count: 19, name: "Outlaws of Thunder Junction Tokens" },
  aotj: { count: 54, name: "Outlaws of Thunder Junction Art Series" },
  totc: { count: 41, name: "Outlaws of Thunder Junction Commander Tokens" },
  otc: { count: 342, name: "Outlaws of Thunder Junction Commander" },
  tbig: { count: 7, name: "The Big Score Tokens" },
  big: { count: 95, name: "The Big Score" },
  otj: { count: 374, name: "Outlaws of Thunder Junction" },
  totp: { count: 5, name: "Breaking News Tokens" },
  otp: { count: 80, name: "Breaking News" },
  pip: { count: 1068, name: "Fallout" },
  tpip: { count: 22, name: "Fallout Tokens" },
  ymkm: { count: 30, name: "Alchemy: Murders at Karlov Manor " },
  clu: { count: 284, name: "Ravnica: Clue Edition" },
  fclu: { count: 10, name: "Ravnica: Clue Edition Front Cards" },
  pss4: { count: 5, name: "MKM Standard Showdown" },
  amkm: { count: 49, name: "Murders at Karlov Manor Art Series" },
  pmkm: { count: 180, name: "Murders at Karlov Manor Promos" },
  tmkc: { count: 31, name: "Murders at Karlov Manor Commander Tokens" },
  tmkm: { count: 21, name: "Murders at Karlov Manor Tokens" },
  wmkm: { count: 4, name: "MKM Japanese Promo Tokens" },
  mkm: { count: 450, name: "Murders at Karlov Manor" },
  mkc: { count: 358, name: "Murders at Karlov Manor Commander" },
  pl24: { count: 7, name: "Year of the Dragon 2024" },
  trvr: { count: 20, name: "Ravnica Remastered Tokens" },
  rvr: { count: 531, name: "Ravnica Remastered" },
  pf24: { count: 1, name: "MagicFest 2024" },
  pw24: { count: 18, name: "Wizards Play Network 2024" },
  ylci: { count: 30, name: "Alchemy: Ixalan" },
  alci: { count: 81, name: "The Lost Caverns of Ixalan Art Series" },
  spg: { count: 89, name: "Special Guests" },
  plci: { count: 136, name: "The Lost Caverns of Ixalan Promos" },
  trex: { count: 2, name: "Jurassic World Collection Tokens" },
  tlci: { count: 20, name: "The Lost Caverns of Ixalan Tokens" },
  pmat: { count: 8, name: "March of the Machine: The Aftermath Promos" },
  rex: { count: 45, name: "Jurassic World Collection" },
  tlcc: { count: 18, name: "The Lost Caverns of Ixalan Commander Tokens" },
  lcc: { count: 370, name: "The Lost Caverns of Ixalan Commander" },
  slci: { count: 1, name: "The Lost Caverns of Ixalan Substitute Cards" },
  lci: { count: 416, name: "The Lost Caverns of Ixalan" },
  who: { count: 1178, name: "Doctor Who" },
  twho: { count: 64, name: "Doctor Who Tokens" },
  ywoe: { count: 30, name: "Alchemy: Wilds of Eldraine" },
  pwoe: { count: 160, name: "Wilds of Eldraine Promos" },
  wot: { count: 103, name: "Wilds of Eldraine: Enchanting Tales" },
  woc: { count: 173, name: "Wilds of Eldraine Commander" },
  awoe: { count: 81, name: "Wilds of Eldraine Art Series" },
  wwoe: { count: 6, name: "WOE Japanese Promo Tokens" },
  twoc: { count: 17, name: "Wilds of Eldraine Commander Tokens" },
  twoe: { count: 18, name: "Wilds of Eldraine Tokens" },
  ptsr: { count: 3, name: "Time Spiral Remastered Promos" },
  pmda: { count: 4, name: "Magic × Duel Masters Promos" },
  woe: { count: 381, name: "Wilds of Eldraine" },
  p30t: { count: 2, name: "30th Anniversary Celebration Tokyo" },
  acmm: { count: 81, name: "Commander Masters Art Series" },
  tcmm: { count: 81, name: "Commander Masters Tokens" },
  cmm: { count: 1067, name: "Commander Masters" },
  ph22: { count: 5, name: "2022 Heroes of the Realm" },
  ea3: { count: 25, name: "Explorer Anthology 3" },
  ha7: { count: 25, name: "Historic Anthology 7" },
  pf23: { count: 4, name: "MagicFest 2023" },
  pltr: { count: 86, name: "Tales of Middle-earth Promos" },
  ltc: { count: 591, name: "Tales of Middle-earth Commander" },
  fltr: { count: 10, name: "Tales of Middle-earth Front Cards" },
  altr: { count: 81, name: "Tales of Middle-earth Art Series" },
  tltr: { count: 25, name: "Tales of Middle-earth Tokens" },
  ltr: { count: 856, name: "The Lord of the Rings: Tales of Middle-earth" },
  tltc: { count: 15, name: "Tales of Middle-earth Commander Tokens" },
  mat: { count: 230, name: "March of the Machine: The Aftermath" },
  fmom: { count: 5, name: "March of the Machine Jumpstart Front Cards" },
  tmoc: { count: 46, name: "March of the Machine Commander Tokens" },
  tmul: { count: 2, name: "Multiverse Legends Tokens" },
  mom: { count: 387, name: "March of the Machine" },
  pmom: { count: 134, name: "March of the Machine Promos" },
  smom: { count: 1, name: "March of the Machine Substitute Cards" },
  wmom: { count: 12, name: "MOM Japanese Promo Tokens" },
  amom: { count: 81, name: "March of the Machine Art Series" },
  mul: { count: 261, name: "Multiverse Legends" },
  tmom: { count: 23, name: "March of the Machine Tokens" },
  moc: { count: 450, name: "March of the Machine Commander" },
  sis: { count: 76, name: "Shadows of the Past" },
  sir: { count: 294, name: "Shadows over Innistrad Remastered" },
  yone: { count: 30, name: "Alchemy: Phyrexia" },
  slp: { count: 34, name: "Secret Lair Showdown" },
  da1: { count: 368, name: "Unknown Event" },
  pl23: { count: 6, name: "Year of the Rabbit 2023" },
  pone: { count: 160, name: "Phyrexia: All Will Be One Promos" },
  tonc: { count: 23, name: "Phyrexia: All Will Be One Commander Tokens" },
  tone: { count: 14, name: "Phyrexia: All Will Be One Tokens" },
  fone: { count: 5, name: "Phyrexia: All Will Be One Jumpstart Front Cards" },
  aone: { count: 81, name: "Phyrexia: All Will Be One Art Series" },
  onc: { count: 174, name: "Phyrexia: All Will Be One Commander" },
  mone: { count: 5, name: "Phyrexia: All Will Be One Minigames" },
  one: { count: 479, name: "Phyrexia: All Will Be One" },
  wone: { count: 6, name: "ONE Japanese Promo Tokens" },
  dmr: { count: 457, name: "Dominaria Remastered" },
  tdmr: { count: 14, name: "Dominaria Remastered Tokens" },
  pr23: { count: 3, name: "Regional Championship Qualifiers 2023" },
  pw23: { count: 11, name: "Wizards Play Network 2023" },
  p23: { count: 10, name: "Judge Gift Cards 2023" },
  ybro: { count: 31, name: "Alchemy: The Brothers' War" },
  ea2: { count: 25, name: "Explorer Anthology 2" },
  tscd: { count: 27, name: "Starter Commander Deck Tokens" },
  scd: { count: 352, name: "Starter Commander Decks" },
  fj22: { count: 46, name: "Jumpstart 2022 Front Cards" },
  j22: { count: 835, name: "Jumpstart 2022" },
  "30a": { count: 594, name: "30th Anniversary Edition" },
  t30a: { count: 16, name: "30th Anniversary Tokens" },
  pewk: { count: 6, name: "Eternal Weekend" },
  brc: { count: 209, name: "The Brothers' War Commander" },
  brr: { count: 189, name: "The Brothers' War Retro Artifacts" },
  pbro: { count: 171, name: "The Brothers' War Promos" },
  tbot: { count: 2, name: "Transformers Tokens" },
  bot: { count: 29, name: "Transformers" },
  ptbro: { count: 3, name: "The Brothers' War Southeast Asia Tokens" },
  tbrc: { count: 14, name: "The Brothers' War Commander Tokens" },
  mbro: { count: 3, name: "The Brothers' War Minigames" },
  tbro: { count: 12, name: "The Brothers' War Tokens" },
  abro: { count: 81, name: "The Brothers' War Art Series" },
  fbro: { count: 5, name: "The Brothers' War Jumpstart Front Cards" },
  sbro: { count: 1, name: "The Brothers' War Substitute Cards" },
  bro: { count: 399, name: "The Brothers' War" },
  slc: { count: 31, name: "Secret Lair 30th Anniversary Countdown Kit" },
  tgn3: { count: 10, name: "Game Night: Free-for-All Tokens" },
  gn3: { count: 135, name: "Game Night: Free-for-All" },
  ulst: { count: 62, name: "The List (Unfinity Foil Edition)" },
  sunf: { count: 48, name: "Unfinity Sticker Sheets" },
  unf: { count: 639, name: "Unfinity" },
  tunf: { count: 14, name: "Unfinity Tokens" },
  "40k": { count: 618, name: "Warhammer 40,000 Commander" },
  t40k: { count: 31, name: "Warhammer 40,000 Tokens" },
  ydmu: { count: 39, name: "Alchemy: Dominaria" },
  prcq: { count: 3, name: "Regional Championship Qualifiers 2022" },
  p30h: { count: 10, name: "30th Anniversary History Promos" },
  pdmu: { count: 161, name: "Dominaria United Promos" },
  ptdmu: { count: 3, name: "Dominaria United Southeast Asia Tokens" },
  admu: { count: 81, name: "Dominaria United Art Series" },
  mdmu: { count: 3, name: "Dominaria United Minigames" },
  dmc: { count: 240, name: "Dominaria United Commander" },
  tdmc: { count: 12, name: "Dominaria United Commander Tokens" },
  dmu: { count: 453, name: "Dominaria United" },
  wdmu: { count: 5, name: "DMU Japanese Promo Tokens" },
  fdmu: { count: 10, name: "Dominaria United Jumpstart Front Cards" },
  tdmu: { count: 26, name: "Dominaria United Tokens" },
  p30a: { count: 30, name: "30th Anniversary Play Promos" },
  p30m: { count: 5, name: "30th Anniversary Misc Promos" },
  psvc: { count: 3, name: "Summer Vacation Promos 2022" },
  ph21: { count: 4, name: "2021 Heroes of the Realm" },
  ea1: { count: 20, name: "Explorer Anthology 1" },
  ha6: { count: 20, name: "Historic Anthology 6" },
  sch: { count: 32, name: "Store Championships" },
  t2x2: { count: 24, name: "Double Masters 2022 Tokens" },
  "2x2": { count: 579, name: "Double Masters 2022" },
  hbg: { count: 436, name: "Alchemy Horizons: Baldur's Gate" },
  plg22: { count: 2, name: "Love Your LGS 2022" },
  pclb: { count: 104, name: "Battle for Baldur's Gate Promos" },
  mclb: {
    count: 3,
    name: "Commander Legends: Battle for Baldur's Gate Minigames",
  },
  tclb: { count: 51, name: "Battle for Baldur's Gate Tokens" },
  aclb: { count: 81, name: "Battle for Baldur's Gate Art Series" },
  clb: { count: 936, name: "Commander Legends: Battle for Baldur's Gate" },
  ysnc: { count: 30, name: "Alchemy: New Capenna" },
  ptsnc: { count: 6, name: "Streets of New Capenna Southeast Asia Tokens" },
  pncc: { count: 75, name: "New Capenna Commander Promos" },
  tsnc: { count: 17, name: "Streets of New Capenna Tokens" },
  snc: { count: 513, name: "Streets of New Capenna" },
  ncc: { count: 447, name: "New Capenna Commander" },
  psnc: { count: 161, name: "Streets of New Capenna Promos" },
  msnc: { count: 3, name: "Streets of New Capenna Minigames" },
  asnc: { count: 81, name: "New Capenna Art Series" },
  tncc: { count: 36, name: "New Capenna Commander Tokens" },
  gdy: { count: 9, name: "Game Day Promos" },
  q07: { count: 1, name: "Challenger Decks 2022" },
  yneo: { count: 30, name: "Alchemy: Kamigawa" },
  pw22: { count: 6, name: "Wizards Play Network 2022" },
  slx: { count: 23, name: "Universes Within" },
  pl22: { count: 5, name: "Year of the Tiger 2022" },
  pneo: { count: 148, name: "Kamigawa: Neon Dynasty Promos" },
  mneo: { count: 3, name: "Kamigawa: Neon Dynasty Minigames" },
  sneo: { count: 9, name: "Kamigawa: Neon Dynasty Substitute Cards" },
  tneo: { count: 19, name: "Kamigawa: Neon Dynasty Tokens" },
  tnec: { count: 12, name: "Neon Dynasty Commander Tokens" },
  neo: { count: 531, name: "Kamigawa: Neon Dynasty" },
  nec: { count: 179, name: "Neon Dynasty Commander" },
  aneo: { count: 81, name: "Neon Dynasty Art Series" },
  cc2: { count: 9, name: "Commander Collection: Black" },
  dbl: { count: 535, name: "Innistrad: Double Feature" },
  p22: { count: 10, name: "Judge Gift Cards 2022" },
  ymid: { count: 63, name: "Alchemy: Innistrad" },
  pvow: { count: 114, name: "Innistrad: Crimson Vow Promos" },
  tvow: { count: 21, name: "Innistrad: Crimson Vow Tokens" },
  ovoc: { count: 2, name: "Crimson Vow Commander Display Commanders" },
  tvoc: { count: 6, name: "Crimson Vow Commander Tokens" },
  mvow: { count: 3, name: "Innistrad: Crimson Vow Minigames" },
  svow: { count: 9, name: "Innistrad: Crimson Vow Substitute Cards" },
  avow: { count: 81, name: "Crimson Vow Art Series" },
  voc: { count: 188, name: "Crimson Vow Commander" },
  vow: { count: 423, name: "Innistrad: Crimson Vow" },
  q06: { count: 10, name: "Pioneer Challenger Decks 2021" },
  smid: { count: 9, name: "Innistrad: Midnight Hunt Substitute Cards" },
  tmic: { count: 11, name: "Midnight Hunt Commander Tokens" },
  mic: { count: 187, name: "Midnight Hunt Commander" },
  pmid: { count: 155, name: "Innistrad: Midnight Hunt Promos" },
  amid: { count: 81, name: "Midnight Hunt Art Series" },
  omic: { count: 2, name: "Midnight Hunt Commander Display Commanders" },
  tmid: { count: 19, name: "Innistrad: Midnight Hunt Tokens" },
  mmid: { count: 3, name: "Innistrad: Midnight Hunt Minigames" },
  mid: { count: 400, name: "Innistrad: Midnight Hunt" },
  j21: { count: 389, name: "Jumpstart: Historic Horizons" },
  cmb2: { count: 121, name: "Mystery Booster Playtest Cards 2021" },
  ph20: { count: 3, name: "2020 Heroes of the Realm" },
  pafr: { count: 240, name: "Adventures in the Forgotten Realms Promos" },
  oafc: { count: 4, name: "Forgotten Realms Commander Display Commanders" },
  aafr: { count: 81, name: "Adventures in the Forgotten Realms Art Series" },
  afc: { count: 331, name: "Forgotten Realms Commander" },
  tafc: { count: 13, name: "Forgotten Realms Commander Tokens" },
  tafr: { count: 22, name: "Adventures in the Forgotten Realms Tokens" },
  mafr: { count: 5, name: "Adventures in the Forgotten Realms Minigames" },
  afr: { count: 424, name: "Adventures in the Forgotten Realms" },
  plg21: { count: 11, name: "Love Your LGS 2021" },
  pmh2: { count: 86, name: "Modern Horizons 2 Promos" },
  amh2: { count: 162, name: "Modern Horizons 2 Art Series" },
  tmh2: { count: 21, name: "Modern Horizons 2 Tokens" },
  mmh2: { count: 5, name: "Modern Horizons 2 Minigames" },
  pw21: { count: 6, name: "Wizards Play Network 2021" },
  h1r: { count: 40, name: "Modern Horizons 1 Timeshifts" },
  mh2: { count: 494, name: "Modern Horizons 2" },
  ha5: { count: 25, name: "Historic Anthology 5" },
  pstx: { count: 164, name: "Strixhaven: School of Mages Promos" },
  tstx: { count: 9, name: "Strixhaven: School of Mages Tokens" },
  tc21: { count: 30, name: "Commander 2021 Tokens" },
  sstx: { count: 9, name: "Strixhaven: School of Mages Substitute Cards" },
  mstx: { count: 5, name: "Strixhaven: School of Mages Minigames" },
  oc21: { count: 5, name: "Commander 2021 Display Commanders" },
  astx: { count: 162, name: "Strixhaven Art Series" },
  stx: { count: 393, name: "Strixhaven: School of Mages" },
  c21: { count: 409, name: "Commander 2021" },
  sta: { count: 126, name: "Strixhaven Mystical Archive" },
  ttsr: { count: 15, name: "Time Spiral Remastered Tokens" },
  tsr: { count: 411, name: "Time Spiral Remastered" },
  ha4: { count: 25, name: "Historic Anthology 4" },
  pkhm: { count: 158, name: "Kaldheim Promos" },
  mkhm: { count: 5, name: "Kaldheim Minigames" },
  skhm: { count: 9, name: "Kaldheim Substitute Cards" },
  tkhm: { count: 23, name: "Kaldheim Tokens" },
  khc: { count: 119, name: "Kaldheim Commander" },
  khm: { count: 426, name: "Kaldheim" },
  tkhc: { count: 8, name: "Kaldheim Commander Tokens" },
  akhm: { count: 81, name: "Kaldheim Art Series" },
  pl21: { count: 6, name: "Year of the Ox 2021" },
  pj21: { count: 10, name: "Judge Gift Cards 2021" },
  cc1: { count: 8, name: "Commander Collection: Green" },
  pcmr: { count: 6, name: "Commander Legends Promos" },
  cmr: { count: 718, name: "Commander Legends" },
  tcmr: { count: 23, name: "Commander Legends Tokens" },
  klr: { count: 302, name: "Kaladesh Remastered" },
  plst: { count: 4809, name: "The List" },
  pznr: { count: 153, name: "Zendikar Rising Promos" },
  tznc: { count: 11, name: "Zendikar Rising Commander Tokens" },
  tznr: { count: 12, name: "Zendikar Rising Tokens" },
  zne: { count: 30, name: "Zendikar Rising Expeditions" },
  znc: { count: 142, name: "Zendikar Rising Commander" },
  znr: { count: 408, name: "Zendikar Rising" },
  mznr: { count: 5, name: "Zendikar Rising Minigames" },
  aznr: { count: 81, name: "Zendikar Rising Art Series" },
  sznr: { count: 9, name: "Zendikar Rising Substitute Cards" },
  akr: { count: 339, name: "Amonkhet Remastered" },
  anb: { count: 120, name: "Arena Beginner Set" },
  "2xm": { count: 384, name: "Double Masters" },
  t2xm: { count: 31, name: "Double Masters Tokens" },
  ph19: { count: 7, name: "2019 Heroes of the Realm" },
  ajmp: { count: 18, name: "Jumpstart Arena Exclusives" },
  jmp: { count: 497, name: "Jumpstart" },
  pm21: { count: 137, name: "Core Set 2021 Promos" },
  tm21: { count: 20, name: "Core Set 2021 Tokens" },
  m21: { count: 397, name: "Core Set 2021" },
  ss3: { count: 8, name: "Signature Spellbook: Chandra" },
  fjmp: { count: 46, name: "Jumpstart Front Cards" },
  slu: { count: 16, name: "Secret Lair: Ultimate Edition" },
  ha3: { count: 27, name: "Historic Anthology 3" },
  plg20: { count: 2, name: "Love Your LGS 2020" },
  piko: { count: 137, name: "Ikoria: Lair of Behemoths Promos" },
  iko: { count: 390, name: "Ikoria: Lair of Behemoths" },
  tiko: { count: 15, name: "Ikoria: Lair of Behemoths Tokens" },
  oc20: { count: 5, name: "Commander 2020 Oversized" },
  tc20: { count: 21, name: "Commander 2020 Tokens" },
  c20: { count: 322, name: "Commander 2020" },
  ha2: { count: 25, name: "Historic Anthology 2" },
  tund: { count: 6, name: "Unsanctioned Tokens" },
  und: { count: 96, name: "Unsanctioned" },
  pthb: { count: 137, name: "Theros Beyond Death Promos" },
  tthb: { count: 14, name: "Theros Beyond Death Tokens" },
  thb: { count: 358, name: "Theros Beyond Death" },
  j20: { count: 10, name: "Judge Gift Cards 2020" },
  pf20: { count: 6, name: "MagicFest 2020" },
  sld: { count: 1709, name: "Secret Lair Drop" },
  ha1: { count: 20, name: "Historic Anthology 1" },
  tgn2: { count: 3, name: "Game Night 2019 Tokens" },
  gn2: { count: 64, name: "Game Night 2019" },
  cmb1: { count: 121, name: "Mystery Booster Playtest Cards 2019" },
  ptg: { count: 3, name: "Ponies: The Galloping" },
  peld: { count: 138, name: "Throne of Eldraine Promos" },
  eld: { count: 399, name: "Throne of Eldraine" },
  pwcs: { count: 32, name: "Planeswalker Championship Promos" },
  teld: { count: 20, name: "Throne of Eldraine Tokens" },
  oc19: { count: 4, name: "Commander 2019 Oversized" },
  c19: { count: 302, name: "Commander 2019" },
  tc19: { count: 29, name: "Commander 2019 Tokens" },
  ph18: { count: 5, name: "2018 Heroes of the Realm" },
  ps19: { count: 5, name: "San Diego Comic-Con 2019" },
  pm20: { count: 144, name: "Core Set 2020 Promos" },
  tm20: { count: 12, name: "Core Set 2020 Tokens" },
  ppp1: { count: 5, name: "M20 Promo Packs" },
  m20: { count: 345, name: "Core Set 2020" },
  ss2: { count: 8, name: "Signature Spellbook: Gideon" },
  pmh1: { count: 2, name: "Modern Horizons Promos" },
  mh1: { count: 255, name: "Modern Horizons" },
  amh1: { count: 54, name: "Modern Horizons Art Series" },
  tmh1: { count: 21, name: "Modern Horizons Tokens" },
  pwar: { count: 176, name: "War of the Spark Promos" },
  twar: { count: 19, name: "War of the Spark Tokens" },
  war: { count: 312, name: "War of the Spark" },
  j19: { count: 8, name: "Judge Gift Cards 2019" },
  prw2: { count: 10, name: "RNA Ravnica Weekend" },
  gk2: { count: 133, name: "RNA Guild Kit" },
  tgk2: { count: 9, name: "RNA Guild Kit Tokens" },
  prna: { count: 81, name: "Ravnica Allegiance Promos" },
  trna: { count: 13, name: "Ravnica Allegiance Tokens" },
  rna: { count: 273, name: "Ravnica Allegiance" },
  pf19: { count: 7, name: "MagicFest 2019" },
  opca: { count: 86, name: "Planechase Anthology Planes" },
  puma: { count: 40, name: "Ultimate Box Topper" },
  tuma: { count: 16, name: "Ultimate Masters Tokens" },
  uma: { count: 254, name: "Ultimate Masters" },
  gnt: { count: 68, name: "Game Night" },
  g18: { count: 5, name: "M19 Gift Pack" },
  prwk: { count: 10, name: "GRN Ravnica Weekend" },
  gk1: { count: 127, name: "GRN Guild Kit" },
  tgk1: { count: 10, name: "GRN Guild Kit Tokens" },
  pgrn: { count: 84, name: "Guilds of Ravnica Promos" },
  tgrn: { count: 8, name: "Guilds of Ravnica Tokens" },
  grn: { count: 273, name: "Guilds of Ravnica" },
  med: { count: 24, name: "Mythic Edition" },
  tmed: { count: 16, name: "Mythic Edition Tokens" },
  oc18: { count: 4, name: "Commander 2018 Oversized" },
  tc18: { count: 26, name: "Commander 2018 Tokens" },
  c18: { count: 307, name: "Commander 2018" },
  ph17: { count: 3, name: "2017 Heroes of the Realm" },
  ps18: { count: 5, name: "San Diego Comic-Con 2018" },
  xana: { count: 20, name: "Arena New Player Experience Extras" },
  ana: { count: 40, name: "Arena New Player Experience" },
  pana: { count: 78, name: "MTG Arena Promos" },
  oana: { count: 14, name: "Arena New Player Experience Cards" },
  pm19: { count: 95, name: "Core Set 2019 Promos" },
  pss3: { count: 5, name: "M19 Standard Showdown" },
  tm19: { count: 18, name: "Core Set 2019 Tokens" },
  m19: { count: 314, name: "Core Set 2019" },
  gs1: { count: 41, name: "Global Series Jiang Yanggu & Mu Yanling" },
  ss1: { count: 8, name: "Signature Spellbook: Jace" },
  pbbd: { count: 22, name: "Battlebond Promos" },
  tbbd: { count: 8, name: "Battlebond Tokens" },
  tcm2: { count: 19, name: "Commander Anthology Volume II Tokens" },
  bbd: { count: 256, name: "Battlebond" },
  cm2: { count: 312, name: "Commander Anthology Volume II" },
  pdom: { count: 118, name: "Dominaria Promos" },
  dom: { count: 280, name: "Dominaria" },
  tdom: { count: 16, name: "Dominaria Tokens" },
  ddu: { count: 76, name: "Duel Decks: Elves vs. Inventors" },
  tddu: { count: 4, name: "Duel Decks: Elves vs. Inventors Tokens" },
  a25: { count: 249, name: "Masters 25" },
  ta25: { count: 16, name: "Masters 25 Tokens" },
  plny: { count: 1, name: "Lunar New Year 2018 " },
  pnat: { count: 1, name: "Nationals Promos" },
  prix: { count: 98, name: "Rivals of Ixalan Promos" },
  trix: { count: 7, name: "Rivals of Ixalan Tokens" },
  rix: { count: 205, name: "Rivals of Ixalan" },
  j18: { count: 8, name: "Judge Gift Cards 2018" },
  f18: { count: 3, name: "Friday Night Magic 2018" },
  pust: { count: 1, name: "Unstable Promos" },
  tust: { count: 20, name: "Unstable Tokens" },
  ust: { count: 268, name: "Unstable" },
  tima: { count: 7, name: "Iconic Masters Tokens" },
  pxtc: { count: 10, name: "XLN Treasure Chest" },
  v17: { count: 16, name: "From the Vault: Transform" },
  e02: { count: 48, name: "Explorers of Ixalan" },
  ima: { count: 249, name: "Iconic Masters" },
  ddt: { count: 63, name: "Duel Decks: Merfolk vs. Goblins" },
  tddt: { count: 3, name: "Duel Decks: Merfolk vs. Goblins Tokens" },
  g17: { count: 5, name: "2017 Gift Pack" },
  pxln: { count: 120, name: "Ixalan Promos" },
  xln: { count: 289, name: "Ixalan" },
  txln: { count: 11, name: "Ixalan Tokens" },
  pss2: { count: 5, name: "XLN Standard Showdown" },
  h17: { count: 4, name: "HasCon 2017" },
  phtr: { count: 3, name: "2016 Heroes of the Realm" },
  te01: { count: 5, name: "Archenemy: Nicol Bolas Tokens" },
  oc17: { count: 4, name: "Commander 2017 Oversized" },
  c17: { count: 309, name: "Commander 2017" },
  tc17: { count: 11, name: "Commander 2017 Tokens" },
  ps17: { count: 6, name: "San Diego Comic-Con 2017" },
  phou: { count: 62, name: "Hour of Devastation Promos" },
  hou: { count: 209, name: "Hour of Devastation" },
  thou: { count: 14, name: "Hour of Devastation Tokens" },
  oe01: { count: 20, name: "Archenemy: Nicol Bolas Schemes" },
  e01: { count: 106, name: "Archenemy: Nicol Bolas" },
  tcma: { count: 20, name: "Commander Anthology Tokens" },
  cma: { count: 320, name: "Commander Anthology" },
  pakh: { count: 77, name: "Amonkhet Promos" },
  akh: { count: 287, name: "Amonkhet" },
  takh: { count: 27, name: "Amonkhet Tokens" },
  mp2: { count: 54, name: "Amonkhet Invocations" },
  w17: { count: 30, name: "Welcome Deck 2017" },
  dds: { count: 65, name: "Duel Decks: Mind vs. Might" },
  tdds: { count: 7, name: "Duel Decks: Mind vs. Might Tokens" },
  mm3: { count: 249, name: "Modern Masters 2017" },
  tmm3: { count: 21, name: "Modern Masters 2017 Tokens" },
  paer: { count: 65, name: "Aether Revolt Promos" },
  taer: { count: 4, name: "Aether Revolt Tokens" },
  aer: { count: 197, name: "Aether Revolt" },
  l17: { count: 1, name: "League Tokens 2017" },
  f17: { count: 12, name: "Friday Night Magic 2017" },
  j17: { count: 9, name: "Judge Gift Cards 2017" },
  tpca: { count: 19, name: "Planechase Anthology Tokens" },
  pca: { count: 156, name: "Planechase Anthology" },
  pz2: { count: 282, name: "Treasure Chest" },
  oc16: { count: 5, name: "Commander 2016 Oversized" },
  tc16: { count: 21, name: "Commander 2016 Tokens" },
  c16: { count: 351, name: "Commander 2016" },
  ps16: { count: 5, name: "San Diego Comic-Con 2016" },
  pkld: { count: 83, name: "Kaladesh Promos" },
  kld: { count: 278, name: "Kaladesh" },
  tkld: { count: 13, name: "Kaladesh Tokens" },
  mps: { count: 54, name: "Kaladesh Inventions" },
  ddr: { count: 76, name: "Duel Decks: Nissa vs. Ob Nixilis" },
  cn2: { count: 222, name: "Conspiracy: Take the Crown" },
  tcn2: { count: 12, name: "Conspiracy: Take the Crown Tokens" },
  v16: { count: 16, name: "From the Vault: Lore" },
  pemn: { count: 77, name: "Eldritch Moon Promos" },
  emn: { count: 208, name: "Eldritch Moon" },
  temn: { count: 11, name: "Eldritch Moon Tokens" },
  tema: { count: 16, name: "Eternal Masters Tokens" },
  ema: { count: 249, name: "Eternal Masters" },
  psoi: { count: 90, name: "Shadows over Innistrad Promos" },
  tsoi: { count: 20, name: "Shadows over Innistrad Tokens" },
  w16: { count: 16, name: "Welcome Deck 2016" },
  soi: { count: 302, name: "Shadows over Innistrad" },
  ddq: { count: 80, name: "Duel Decks: Blessed vs. Cursed" },
  togw: { count: 11, name: "Oath of the Gatewatch Tokens" },
  ogw: { count: 187, name: "Oath of the Gatewatch" },
  pogw: { count: 65, name: "Oath of the Gatewatch Promos" },
  l16: { count: 1, name: "League Tokens 2016" },
  j16: { count: 8, name: "Judge Gift Cards 2016" },
  f16: { count: 12, name: "Friday Night Magic 2016" },
  pz1: { count: 149, name: "Legendary Cube Prize Pack" },
  oc15: { count: 5, name: "Commander 2015 Oversized" },
  tc15: { count: 25, name: "Commander 2015 Tokens" },
  c15: { count: 342, name: "Commander 2015" },
  tbfz: { count: 14, name: "Battle for Zendikar Tokens" },
  pbfz: { count: 90, name: "Battle for Zendikar Promos" },
  bfz: { count: 299, name: "Battle for Zendikar" },
  pss1: { count: 5, name: "BFZ Standard Series" },
  exp: { count: 45, name: "Zendikar Expeditions" },
  ddp: { count: 80, name: "Duel Decks: Zendikar vs. Eldrazi" },
  v15: { count: 15, name: "From the Vault: Angels" },
  cp3: { count: 6, name: "Magic Origins Clash Pack" },
  pori: { count: 54, name: "Magic Origins Promos" },
  tori: { count: 15, name: "Magic Origins Tokens" },
  ori: { count: 288, name: "Magic Origins" },
  ps15: { count: 5, name: "San Diego Comic-Con 2015" },
  mm2: { count: 249, name: "Modern Masters 2015" },
  tmm2: { count: 16, name: "Modern Masters 2015 Tokens" },
  tpr: { count: 269, name: "Tempest Remastered" },
  ptkdf: { count: 4, name: "Tarkir Dragonfury" },
  pdtk: { count: 51, name: "Dragons of Tarkir Promos" },
  tdtk: { count: 8, name: "Dragons of Tarkir Tokens" },
  dtk: { count: 264, name: "Dragons of Tarkir" },
  ddo: { count: 67, name: "Duel Decks: Elspeth vs. Kiora" },
  pfrf: { count: 43, name: "Fate Reforged Promos" },
  cp2: { count: 6, name: "Fate Reforged Clash Pack" },
  frf: { count: 191, name: "Fate Reforged" },
  tfrf: { count: 4, name: "Fate Reforged Tokens" },
  ugin: { count: 26, name: "Ugin's Fate" },
  l15: { count: 1, name: "League Tokens 2015" },
  f15: { count: 12, name: "Friday Night Magic 2015" },
  j15: { count: 8, name: "Judge Gift Cards 2015" },
  tjvc: { count: 1, name: "Duel Decks Anthology: Jace vs. Chandra Tokens" },
  tdvd: { count: 3, name: "Duel Decks Anthology: Divine vs. Demonic Tokens" },
  tgvl: { count: 4, name: "Duel Decks Anthology: Garruk vs. Liliana Tokens" },
  evg: { count: 62, name: "Duel Decks Anthology: Elves vs. Goblins" },
  dvd: { count: 62, name: "Duel Decks Anthology: Divine vs. Demonic" },
  jvc: { count: 62, name: "Duel Decks Anthology: Jace vs. Chandra" },
  tevg: { count: 3, name: "Duel Decks Anthology: Elves vs. Goblins Tokens" },
  gvl: { count: 63, name: "Duel Decks Anthology: Garruk vs. Liliana" },
  oc14: { count: 5, name: "Commander 2014 Oversized" },
  tc14: { count: 36, name: "Commander 2014 Tokens" },
  c14: { count: 337, name: "Commander 2014" },
  pktk: { count: 56, name: "Khans of Tarkir Promos" },
  tktk: { count: 13, name: "Khans of Tarkir Tokens" },
  ktk: { count: 293, name: "Khans of Tarkir" },
  ddn: { count: 82, name: "Duel Decks: Speed vs. Cunning" },
  v14: { count: 15, name: "From the Vault: Annihilation" },
  m15: { count: 284, name: "Magic 2015" },
  tm15: { count: 14, name: "Magic 2015 Tokens" },
  cp1: { count: 6, name: "Magic 2015 Clash Pack" },
  pm15: { count: 14, name: "Magic 2015 Promos" },
  ppc1: { count: 2, name: "M15 Prerelease Challenge" },
  pdp15: { count: 2, name: "Duels of the Planeswalkers 2015 Promos " },
  ps14: { count: 6, name: "San Diego Comic-Con 2014" },
  vma: { count: 325, name: "Vintage Masters" },
  pcns: { count: 1, name: "Conspiracy Promos" },
  tcns: { count: 9, name: "Conspiracy Tokens" },
  cns: { count: 210, name: "Conspiracy" },
  tmd1: { count: 4, name: "Modern Event Deck 2014 Tokens" },
  md1: { count: 26, name: "Modern Event Deck 2014" },
  tdag: { count: 15, name: "Defeat a God" },
  thp3: { count: 8, name: "Journey into Nyx Hero's Path" },
  tjou: { count: 6, name: "Journey into Nyx Tokens" },
  jou: { count: 165, name: "Journey into Nyx" },
  pjou: { count: 10, name: "Journey into Nyx Promos" },
  tddm: { count: 1, name: "Duel Decks: Jace vs. Vraska Tokens" },
  ddm: { count: 88, name: "Duel Decks: Jace vs. Vraska" },
  tbth: { count: 15, name: "Battle the Horde" },
  bng: { count: 165, name: "Born of the Gods" },
  tbng: { count: 11, name: "Born of the Gods Tokens" },
  thp2: { count: 7, name: "Born of the Gods Hero's Path" },
  pbng: { count: 9, name: "Born of the Gods Promos" },
  l14: { count: 4, name: "League Tokens 2014" },
  j14: { count: 14, name: "Judge Gift Cards 2014" },
  f14: { count: 12, name: "Friday Night Magic 2014" },
  oc13: { count: 15, name: "Commander 2013 Oversized" },
  c13: { count: 356, name: "Commander 2013" },
  tfth: { count: 15, name: "Face the Hydra" },
  thp1: { count: 7, name: "Theros Hero's Path" },
  tths: { count: 11, name: "Theros Tokens" },
  ths: { count: 249, name: "Theros" },
  pths: { count: 10, name: "Theros Promos" },
  ddl: { count: 81, name: "Duel Decks: Heroes vs. Monsters" },
  tddl: { count: 2, name: "Duel Decks: Heroes vs. Monsters Tokens" },
  v13: { count: 20, name: "From the Vault: Twenty" },
  m14: { count: 249, name: "Magic 2014" },
  tm14: { count: 13, name: "Magic 2014 Tokens" },
  pm14: { count: 6, name: "Magic 2014 Promos" },
  psdc: { count: 5, name: "San Diego Comic-Con 2013" },
  mma: { count: 229, name: "Modern Masters" },
  tmma: { count: 16, name: "Modern Masters Tokens" },
  dgm: { count: 156, name: "Dragon's Maze" },
  tdgm: { count: 1, name: "Dragon's Maze Tokens" },
  pdgm: { count: 6, name: "Dragon's Maze Promos" },
  wmc: { count: 5, name: "World Magic Cup Qualifiers" },
  ddk: { count: 80, name: "Duel Decks: Sorin vs. Tibalt" },
  tddk: { count: 1, name: "Duel Decks: Sorin vs. Tibalt Tokens" },
  gtc: { count: 249, name: "Gatecrash" },
  tgtc: { count: 8, name: "Gatecrash Tokens" },
  pgtc: { count: 10, name: "Gatecrash Promos" },
  pdp14: { count: 3, name: "Duels of the Planeswalkers 2014 Promos " },
  l13: { count: 4, name: "League Tokens 2013" },
  f13: { count: 12, name: "Friday Night Magic 2013" },
  j13: { count: 9, name: "Judge Gift Cards 2013" },
  ocm1: { count: 10, name: "Commander's Arsenal Oversized" },
  cm1: { count: 18, name: "Commander's Arsenal" },
  rtr: { count: 274, name: "Return to Ravnica" },
  prtr: { count: 10, name: "Return to Ravnica Promos" },
  trtr: { count: 12, name: "Return to Ravnica Tokens" },
  tddj: { count: 1, name: "Duel Decks: Izzet vs. Golgari Tokens" },
  ddj: { count: 90, name: "Duel Decks: Izzet vs. Golgari" },
  v12: { count: 15, name: "From the Vault: Realms" },
  tm13: { count: 11, name: "Magic 2013 Tokens" },
  m13: { count: 249, name: "Magic 2013" },
  pm13: { count: 6, name: "Magic 2013 Promos" },
  opc2: { count: 40, name: "Planechase 2012 Planes" },
  pc2: { count: 156, name: "Planechase 2012" },
  tavr: { count: 8, name: "Avacyn Restored Tokens" },
  avr: { count: 244, name: "Avacyn Restored" },
  phel: { count: 6, name: "Open the Helvault" },
  pavr: { count: 6, name: "Avacyn Restored Promos" },
  ddi: { count: 77, name: "Duel Decks: Venser vs. Koth" },
  tddi: { count: 2, name: "Duel Decks: Venser vs. Koth Tokens" },
  tdka: { count: 4, name: "Dark Ascension Tokens" },
  dka: { count: 158, name: "Dark Ascension" },
  pdka: { count: 5, name: "Dark Ascension Promos" },
  pw12: { count: 3, name: "Wizards Play Network 2012" },
  pdp13: { count: 3, name: "Duels of the Planeswalkers 2013 Promos " },
  pidw: { count: 17, name: "IDW Comics Inserts" },
  l12: { count: 2, name: "League Tokens 2012" },
  j12: { count: 9, name: "Judge Gift Cards 2012" },
  f12: { count: 13, name: "Friday Night Magic 2012" },
  pd3: { count: 30, name: "Premium Deck Series: Graveborn" },
  isd: { count: 264, name: "Innistrad" },
  tisd: { count: 13, name: "Innistrad Tokens" },
  pisd: { count: 5, name: "Innistrad Promos" },
  tddh: { count: 2, name: "Duel Decks: Ajani vs. Nicol Bolas Tokens" },
  ddh: { count: 80, name: "Duel Decks: Ajani vs. Nicol Bolas" },
  v11: { count: 15, name: "From the Vault: Legends" },
  tm12: { count: 7, name: "Magic 2012 Tokens" },
  m12: { count: 249, name: "Magic 2012" },
  pm12: { count: 3, name: "Magic 2012 Promos" },
  ocmd: { count: 15, name: "Commander 2011 Oversized" },
  cmd: { count: 318, name: "Commander 2011" },
  pcmd: { count: 5, name: "Commander 2011 Launch Party" },
  td2: { count: 88, name: "Duel Decks: Mirrodin Pure vs. New Phyrexia" },
  nph: { count: 175, name: "New Phyrexia" },
  tnph: { count: 5, name: "New Phyrexia Tokens" },
  pnph: { count: 4, name: "New Phyrexia Promos" },
  tddg: { count: 1, name: "Duel Decks: Knights vs. Dragons Tokens" },
  ddg: { count: 81, name: "Duel Decks: Knights vs. Dragons" },
  mbs: { count: 155, name: "Mirrodin Besieged" },
  tmbs: { count: 6, name: "Mirrodin Besieged Tokens" },
  pmbs: { count: 4, name: "Mirrodin Besieged Promos" },
  me4: { count: 269, name: "Masters Edition IV" },
  pmps11: { count: 5, name: "Magic Premiere Shop 2011" },
  pdp12: { count: 3, name: "Duels of the Planeswalkers 2012 Promos " },
  pw11: { count: 3, name: "Wizards Play Network 2011" },
  g11: { count: 8, name: "Judge Gift Cards 2011" },
  p11: { count: 7, name: "Magic Player Rewards 2011" },
  olgc: { count: 27, name: "Legacy Championship" },
  f11: { count: 12, name: "Friday Night Magic 2011" },
  ps11: { count: 224, name: "Salvat 2011" },
  pd2: { count: 34, name: "Premium Deck Series: Fire and Lightning" },
  td0: { count: 197, name: "Magic Online Theme Decks" },
  som: { count: 249, name: "Scars of Mirrodin" },
  tsom: { count: 10, name: "Scars of Mirrodin Tokens" },
  psom: { count: 4, name: "Scars of Mirrodin Promos" },
  ddf: { count: 79, name: "Duel Decks: Elspeth vs. Tezzeret" },
  tddf: { count: 1, name: "Duel Decks: Elspeth vs. Tezzeret Tokens" },
  v10: { count: 15, name: "From the Vault: Relics" },
  tm11: { count: 6, name: "Magic 2011 Tokens" },
  m11: { count: 249, name: "Magic 2011" },
  pm11: { count: 6, name: "Magic 2011 Promos" },
  oarc: { count: 45, name: "Archenemy Schemes" },
  arc: { count: 150, name: "Archenemy" },
  dpa: { count: 113, name: "Duels of the Planeswalkers" },
  proe: { count: 4, name: "Rise of the Eldrazi Promos" },
  troe: { count: 7, name: "Rise of the Eldrazi Tokens" },
  roe: { count: 248, name: "Rise of the Eldrazi" },
  dde: { count: 71, name: "Duel Decks: Phyrexia vs. the Coalition" },
  tdde: { count: 3, name: "Duel Decks: Phyrexia vs. the Coalition Tokens" },
  pwwk: { count: 6, name: "Worldwake Promos" },
  twwk: { count: 6, name: "Worldwake Tokens" },
  wwk: { count: 145, name: "Worldwake" },
  pdp10: { count: 2, name: "Duels of the Planeswalkers 2010 Promos " },
  pmps10: { count: 5, name: "Magic Premiere Shop 2010" },
  f10: { count: 12, name: "Friday Night Magic 2010" },
  g10: { count: 8, name: "Judge Gift Cards 2010" },
  p10: { count: 13, name: "Magic Player Rewards 2010" },
  h09: { count: 41, name: "Premium Deck Series: Slivers" },
  ddd: { count: 63, name: "Duel Decks: Garruk vs. Liliana" },
  tddd: { count: 3, name: "Duel Decks: Garruk vs. Liliana Tokens" },
  pzen: { count: 5, name: "Zendikar Promos" },
  tzen: { count: 11, name: "Zendikar Tokens" },
  zen: { count: 269, name: "Zendikar" },
  me3: { count: 230, name: "Masters Edition III" },
  ohop: { count: 40, name: "Planechase Planes" },
  hop: { count: 169, name: "Planechase" },
  phop: { count: 2, name: "Planechase Promos" },
  v09: { count: 15, name: "From the Vault: Exiled" },
  m10: { count: 249, name: "Magic 2010" },
  tm10: { count: 8, name: "Magic 2010 Tokens" },
  pm10: { count: 3, name: "Magic 2010 Promos" },
  parb: { count: 3, name: "Alara Reborn Promos" },
  arb: { count: 145, name: "Alara Reborn" },
  tarb: { count: 4, name: "Alara Reborn Tokens" },
  tddc: { count: 3, name: "Duel Decks: Divine vs. Demonic Tokens" },
  ddc: { count: 62, name: "Duel Decks: Divine vs. Demonic" },
  purl: { count: 10, name: "URL/Convention Promos" },
  pcon: { count: 2, name: "Conflux Promos" },
  tcon: { count: 2, name: "Conflux Tokens" },
  con: { count: 145, name: "Conflux" },
  pbook: { count: 0, name: "Miscellaneous Book Promos" },
  pdtp: { count: 1, name: "Duels of the Planeswalkers 2009 Promos " },
  pmps09: { count: 5, name: "Magic Premiere Shop 2009" },
  p09: { count: 13, name: "Magic Player Rewards 2009" },
  f09: { count: 12, name: "Friday Night Magic 2009" },
  g09: { count: 10, name: "Judge Gift Cards 2009" },
  dd2: { count: 64, name: "Duel Decks: Jace vs. Chandra" },
  tdd2: { count: 1, name: "Duel Decks: Jace vs. Chandra Tokens" },
  pala: { count: 2, name: "Shards of Alara Promos" },
  tala: { count: 10, name: "Shards of Alara Tokens" },
  ala: { count: 250, name: "Shards of Alara" },
  me2: { count: 245, name: "Masters Edition II" },
  drb: { count: 15, name: "From the Vault: Dragons" },
  peve: { count: 2, name: "Eventide Promos" },
  teve: { count: 7, name: "Eventide Tokens" },
  eve: { count: 180, name: "Eventide" },
  pshm: { count: 2, name: "Shadowmoor Promos" },
  shm: { count: 302, name: "Shadowmoor" },
  tshm: { count: 12, name: "Shadowmoor Tokens" },
  p15a: { count: 2, name: "15th Anniversary Cards" },
  pmor: { count: 2, name: "Morningtide Promos" },
  tmor: { count: 3, name: "Morningtide Tokens" },
  mor: { count: 150, name: "Morningtide" },
  pmps08: { count: 6, name: "Magic Premiere Shop 2008" },
  p08: { count: 7, name: "Magic Player Rewards 2008" },
  f08: { count: 12, name: "Friday Night Magic 2008" },
  g08: { count: 5, name: "Judge Gift Cards 2008" },
  dd1: { count: 62, name: "Duel Decks: Elves vs. Goblins" },
  tdd1: { count: 3, name: "Duel Decks: Elves vs. Goblins Tokens" },
  plrw: { count: 3, name: "Lorwyn Promos" },
  lrw: { count: 301, name: "Lorwyn" },
  tlrw: { count: 11, name: "Lorwyn Tokens" },
  me1: { count: 195, name: "Masters Edition" },
  "10e": { count: 510, name: "Tenth Edition" },
  p10e: { count: 3, name: "Tenth Edition Promos" },
  t10e: { count: 6, name: "Tenth Edition Tokens" },
  pfut: { count: 2, name: "Future Sight Promos" },
  fut: { count: 180, name: "Future Sight" },
  pgpx: { count: 20, name: "Grand Prix Promos" },
  ppro: { count: 15, name: "Pro Tour Promos" },
  pplc: { count: 2, name: "Planar Chaos Promos" },
  plc: { count: 165, name: "Planar Chaos" },
  pres: { count: 0, name: "Resale Promos" },
  pmps07: { count: 5, name: "Magic Premiere Shop 2007" },
  g07: { count: 5, name: "Judge Gift Cards 2007" },
  f07: { count: 12, name: "Friday Night Magic 2007" },
  p07: { count: 7, name: "Magic Player Rewards 2007" },
  hho: { count: 22, name: "Happy Holidays" },
  ptsp: { count: 3, name: "Time Spiral Promos" },
  tsp: { count: 301, name: "Time Spiral" },
  tsb: { count: 121, name: "Time Spiral Timeshifted" },
  pcsp: { count: 2, name: "Coldsnap Promos" },
  cst: { count: 62, name: "Coldsnap Theme Decks" },
  csp: { count: 155, name: "Coldsnap" },
  pdis: { count: 2, name: "Dissension Promos" },
  dis: { count: 180, name: "Dissension" },
  pcmp: { count: 12, name: "Champs and States" },
  pgpt: { count: 2, name: "Guildpact Promos" },
  gpt: { count: 167, name: "Guildpact" },
  pal06: { count: 9, name: "Arena League 2006" },
  pmps06: { count: 5, name: "Magic Premiere Shop 2006" },
  pjas: { count: 6, name: "Junior APAC Series" },
  f06: { count: 12, name: "Friday Night Magic 2006" },
  phuk: { count: 60, name: "Hachette UK" },
  pdci: { count: 80, name: "DCI Promos" },
  p06: { count: 7, name: "Magic Player Rewards 2006" },
  g06: { count: 4, name: "Judge Gift Cards 2006" },
  p2hg: { count: 1, name: "Two-Headed Giant Tournament" },
  prav: { count: 2, name: "Ravnica: City of Guilds Promos" },
  rav: { count: 306, name: "Ravnica: City of Guilds" },
  psal: { count: 720, name: "Salvat 2005" },
  p9ed: { count: 2, name: "Ninth Edition Promos" },
  "9ed": { count: 710, name: "Ninth Edition" },
  psok: { count: 2, name: "Saviors of Kamigawa Promos" },
  sok: { count: 165, name: "Saviors of Kamigawa" },
  pbok: { count: 2, name: "Betrayers of Kamigawa Promos" },
  bok: { count: 165, name: "Betrayers of Kamigawa" },
  pmps: { count: 20, name: "Magic Premiere Shop 2005" },
  pal05: { count: 8, name: "Arena League 2005" },
  pjse: { count: 8, name: "Junior Series Europe" },
  f05: { count: 12, name: "Friday Night Magic 2005" },
  g05: { count: 4, name: "Judge Gift Cards 2005" },
  p05: { count: 6, name: "Magic Player Rewards 2005" },
  punh: { count: 1, name: "Unhinged Promos" },
  unh: { count: 168, name: "Unhinged" },
  pchk: { count: 1, name: "Champions of Kamigawa Promos" },
  chk: { count: 307, name: "Champions of Kamigawa" },
  wc04: { count: 103, name: "World Championship Decks 2004" },
  pmrd: { count: 1, name: "Mirrodin Promos" },
  p5dn: { count: 1, name: "Fifth Dawn Promos" },
  "5dn": { count: 165, name: "Fifth Dawn" },
  pdst: { count: 1, name: "Darksteel Promos" },
  dst: { count: 165, name: "Darksteel" },
  pal04: { count: 14, name: "Arena League 2004" },
  p04: { count: 6, name: "Magic Player Rewards 2004" },
  g04: { count: 6, name: "Judge Gift Cards 2004" },
  f04: { count: 12, name: "Friday Night Magic 2004" },
  mrd: { count: 306, name: "Mirrodin" },
  wc03: { count: 142, name: "World Championship Decks 2003" },
  p8ed: { count: 1, name: "Eighth Edition Promos" },
  "8ed": { count: 711, name: "Eighth Edition" },
  pscg: { count: 1, name: "Scourge Promos" },
  scg: { count: 143, name: "Scourge" },
  plgn: { count: 1, name: "Legions Promos" },
  lgn: { count: 145, name: "Legions" },
  pmoa: { count: 85, name: "Magic Online Avatars" },
  pjjt: { count: 12, name: "Japan Junior Tournament" },
  pal03: { count: 8, name: "Arena League 2003" },
  ovnt: { count: 35, name: "Vintage Championship" },
  p03: { count: 7, name: "Magic Player Rewards 2003" },
  f03: { count: 13, name: "Friday Night Magic 2003" },
  g03: { count: 3, name: "Judge Gift Cards 2003" },
  ons: { count: 351, name: "Onslaught" },
  pons: { count: 1, name: "Onslaught Promos" },
  wc02: { count: 153, name: "World Championship Decks 2002" },
  phj: { count: 5, name: "Hobby Japan Promos" },
  prm: { count: 3110, name: "Magic Online Promos" },
  pjud: { count: 1, name: "Judgment Promos" },
  jud: { count: 143, name: "Judgment" },
  ptor: { count: 3, name: "Torment Promos" },
  tor: { count: 143, name: "Torment" },
  pal02: { count: 5, name: "Arena League 2002" },
  pr2: { count: 6, name: "Magic Player Rewards 2002" },
  g02: { count: 2, name: "Judge Gift Cards 2002" },
  f02: { count: 12, name: "Friday Night Magic 2002" },
  dkm: { count: 58, name: "Deckmasters" },
  pody: { count: 1, name: "Odyssey Promos" },
  ody: { count: 353, name: "Odyssey" },
  wc01: { count: 138, name: "World Championship Decks 2001" },
  psdg: { count: 10, name: "Sega Dreamcast Cards" },
  papc: { count: 1, name: "Apocalypse Promos" },
  apc: { count: 143, name: "Apocalypse" },
  "7ed": { count: 708, name: "Seventh Edition" },
  ppls: { count: 1, name: "Planeshift Promos" },
  pls: { count: 146, name: "Planeshift" },
  pal01: { count: 12, name: "Arena League 2001" },
  g01: { count: 2, name: "Judge Gift Cards 2001" },
  mpr: { count: 8, name: "Magic Player Rewards 2001" },
  f01: { count: 7, name: "Friday Night Magic 2001" },
  pinv: { count: 1, name: "Invasion Promos" },
  inv: { count: 353, name: "Invasion" },
  btd: { count: 90, name: "Beatdown Box Set" },
  wc00: { count: 117, name: "World Championship Decks 2000" },
  ppcy: { count: 1, name: "Prophecy Promos" },
  pcy: { count: 144, name: "Prophecy" },
  s00: { count: 20, name: "Starter 2000" },
  pnem: { count: 1, name: "Nemesis Promos" },
  nem: { count: 143, name: "Nemesis" },
  pelp: { count: 15, name: "European Land Program" },
  pal00: { count: 11, name: "Arena League 2000" },
  fnm: { count: 11, name: "Friday Night Magic 2000" },
  g00: { count: 2, name: "Judge Gift Cards 2000" },
  psus: { count: 18, name: "Junior Super Series" },
  brb: { count: 136, name: "Battle Royale Box Set" },
  pmmq: { count: 1, name: "Mercadian Masques Promos" },
  mmq: { count: 350, name: "Mercadian Masques" },
  pwos: { count: 1, name: "Wizards of the Coast Online Store" },
  pwor: { count: 2, name: "World Championship Promos" },
  wc99: { count: 111, name: "World Championship Decks 1999" },
  pgru: { count: 5, name: "Guru" },
  s99: { count: 173, name: "Starter 1999" },
  puds: { count: 1, name: "Urza's Destiny Promos" },
  uds: { count: 143, name: "Urza's Destiny" },
  pptk: { count: 2, name: "Portal: Three Kingdoms Promos" },
  ptk: { count: 180, name: "Portal Three Kingdoms" },
  "6ed": { count: 351, name: "Classic Sixth Edition" },
  pulg: { count: 2, name: "Urza's Legacy Promos" },
  ulg: { count: 143, name: "Urza's Legacy" },
  pal99: { count: 10, name: "Arena League 1999" },
  g99: { count: 1, name: "Judge Gift Cards 1999" },
  ath: { count: 85, name: "Anthologies" },
  pusg: { count: 1, name: "Urza's Saga Promos" },
  usg: { count: 356, name: "Urza's Saga" },
  palp: { count: 15, name: "Asia Pacific Land Program" },
  wc98: { count: 117, name: "World Championship Decks 1998" },
  tugl: { count: 6, name: "Unglued Tokens" },
  ugl: { count: 88, name: "Unglued" },
  p02: { count: 165, name: "Portal Second Age" },
  pexo: { count: 1, name: "Exodus Promos" },
  exo: { count: 143, name: "Exodus" },
  psth: { count: 1, name: "Stronghold Promos" },
  sth: { count: 143, name: "Stronghold" },
  jgp: { count: 3, name: "Judge Gift Cards 1998" },
  ptmp: { count: 1, name: "Tempest Promos" },
  tmp: { count: 350, name: "Tempest" },
  wc97: { count: 131, name: "World Championship Decks 1997" },
  wth: { count: 167, name: "Weatherlight" },
  olep: { count: 83, name: "Oversized League Prizes" },
  por: { count: 257, name: "Portal" },
  pvan: { count: 32, name: "Vanguard Series" },
  pmic: { count: 1, name: "MicroProse Promos" },
  past: { count: 12, name: "Astral Cards" },
  "5ed": { count: 460, name: "Fifth Edition" },
  vis: { count: 167, name: "Visions" },
  itp: { count: 67, name: "Introductory Two-Player Set" },
  mgb: { count: 10, name: "Multiverse Gift Box" },
  mir: { count: 353, name: "Mirage" },
  pred: { count: 1, name: "Redemption Program" },
  pcel: { count: 9, name: "Celebration Cards" },
  parl: { count: 7, name: "Arena League 1996" },
  rqs: { count: 65, name: "Rivals Quick Start Set" },
  plgm: { count: 2, name: "DCI Legend Membership" },
  all: { count: 199, name: "Alliances" },
  ptc: { count: 308, name: "Pro Tour Collector Set" },
  o90p: { count: 10, name: "Oversized 90's Promos" },
  hml: { count: 140, name: "Homelands" },
  rin: { count: 69, name: "Rinascimento" },
  ren: { count: 122, name: "Renaissance" },
  chr: { count: 125, name: "Chronicles" },
  bchr: { count: 125, name: "Chronicles Foreign Black Border" },
  ice: { count: 383, name: "Ice Age" },
  "4bb": { count: 378, name: "Fourth Edition Foreign Black Border" },
  "4ed": { count: 379, name: "Fourth Edition" },
  pmei: { count: 62, name: "Media and Collaboration Promos" },
  fem: { count: 187, name: "Fallen Empires" },
  phpr: { count: 5, name: "HarperPrism Book Promos" },
  drk: { count: 122, name: "The Dark" },
  pdrc: { count: 1, name: "Dragon Con" },
  sum: { count: 306, name: "Summer Magic / Edgar" },
  leg: { count: 310, name: "Legends" },
  "3ed": { count: 306, name: "Revised Edition" },
  fbb: { count: 307, name: "Foreign Black Border" },
  atq: { count: 102, name: "Antiquities" },
  arn: { count: 92, name: "Arabian Nights" },
  cei: { count: 302, name: "Intl. Collectors' Edition" },
  ced: { count: 302, name: "Collectors' Edition" },
  "2ed": { count: 302, name: "Unlimited Edition" },
  leb: { count: 302, name: "Limited Edition Beta" },
  lea: { count: 295, name: "Limited Edition Alpha" },
};

export const userNames = {
  "152135173813698561": "Ben",
  "135410033524604928": "Yems",
  194831804329492480: "Oli",
  "312274225144791052": "Dan",
  "307938372943478785": "Ollie",
  "203238971009007616": "Tom",
};
