"use strict";

export const allSets = {
  dft: { count: 3, name: "Aetherdrift", order: 939 },
  inr: { count: 6, name: "Innistrad Remastered", order: 938 },
  pspl: { count: 1, name: "Spotlight Series", order: 937 },
  pf25: { count: 1, name: "MagicFest 2025", order: 936 },
  pio: { count: 23, name: "Pioneer Masters", order: 935 },
  afdn: { count: 54, name: "Foundations Art Series", order: 934 },
  ffdn: { count: 2, name: "Foundations Front Cards", order: 933 },
  pfdn: { count: 81, name: "Foundations Promos", order: 932 },
  fj25: { count: 46, name: "Foundations Jumpstart Front Cards", order: 931 },
  tfdn: { count: 33, name: "Foundations Tokens", order: 930 },
  j25: { count: 779, name: "Foundations Jumpstart", order: 929 },
  fdc: { count: 3, name: "Foundations Commander", order: 928 },
  fdn: { count: 730, name: "Foundations", order: 927 },
  pltc: {
    count: 4,
    name: "Tales of Middle-earth Deluxe Commander Kit",
    order: 926,
  },
  ydsk: { count: 30, name: "Alchemy: Duskmourn", order: 925 },
  pdsk: { count: 160, name: "Duskmourn: House of Horror Promos", order: 924 },
  dsc: { count: 373, name: "Duskmourn: House of Horror Commander", order: 923 },
  tdsk: { count: 18, name: "Duskmourn: House of Horror Tokens", order: 922 },
  adsk: {
    count: 54,
    name: "Duskmourn: House of Horror Art Series",
    order: 921,
  },
  tdsc: { count: 23, name: "Duskmourn Commander Tokens", order: 920 },
  dsk: { count: 418, name: "Duskmourn: House of Horror", order: 919 },
  yblb: { count: 30, name: "Alchemy: Bloomburrow", order: 918 },
  plg24: { count: 4, name: "Love Your LGS 2024", order: 917 },
  ablb: { count: 54, name: "Bloomburrow Art Series", order: 916 },
  tblc: { count: 41, name: "Bloomburrow Commander Tokens", order: 915 },
  pblb: { count: 160, name: "Bloomburrow Promos", order: 914 },
  tblb: { count: 30, name: "Bloomburrow Tokens", order: 913 },
  mb2: { count: 385, name: "Mystery Booster 2", order: 912 },
  pcbb: { count: 5, name: "Cowboy Bebop", order: 911 },
  blb: { count: 398, name: "Bloomburrow", order: 910 },
  blc: { count: 356, name: "Bloomburrow Commander", order: 909 },
  macr: { count: 2, name: "Assassin's Creed Minigames", order: 908 },
  aacr: { count: 20, name: "Assassin's Creed Art Series", order: 907 },
  acr: { count: 309, name: "Assassin's Creed", order: 906 },
  tacr: { count: 8, name: "Assassin's Creed Tokens", order: 905 },
  pmh3: { count: 80, name: "Modern Horizons 3 Promos", order: 904 },
  smh3: { count: 1, name: "Modern Horizons 3 Substitute Cards", order: 903 },
  amh3: { count: 54, name: "Modern Horizons 3 Art Series", order: 902 },
  tmh3: { count: 43, name: "Modern Horizons 3 Tokens", order: 901 },
  m3c: { count: 398, name: "Modern Horizons 3 Commander", order: 900 },
  tm3c: { count: 28, name: "Modern Horizons 3 Commander Tokens", order: 899 },
  mh3: { count: 528, name: "Modern Horizons 3", order: 898 },
  h2r: { count: 16, name: "Modern Horizons 2 Timeshifts", order: 897 },
  yotj: { count: 30, name: "Alchemy: Outlaws of Thunder Junction", order: 896 },
  potj: { count: 160, name: "Outlaws of Thunder Junction Promos", order: 895 },
  totj: { count: 19, name: "Outlaws of Thunder Junction Tokens", order: 894 },
  aotj: {
    count: 54,
    name: "Outlaws of Thunder Junction Art Series",
    order: 893,
  },
  totc: {
    count: 41,
    name: "Outlaws of Thunder Junction Commander Tokens",
    order: 892,
  },
  otc: {
    count: 342,
    name: "Outlaws of Thunder Junction Commander",
    order: 891,
  },
  tbig: { count: 7, name: "The Big Score Tokens", order: 890 },
  big: { count: 95, name: "The Big Score", order: 889 },
  otj: { count: 374, name: "Outlaws of Thunder Junction", order: 888 },
  totp: { count: 5, name: "Breaking News Tokens", order: 887 },
  otp: { count: 80, name: "Breaking News", order: 886 },
  pip: { count: 1068, name: "Fallout", order: 885 },
  tpip: { count: 22, name: "Fallout Tokens", order: 884 },
  ymkm: { count: 30, name: "Alchemy: Murders at Karlov Manor ", order: 883 },
  clu: { count: 284, name: "Ravnica: Clue Edition", order: 882 },
  fclu: { count: 10, name: "Ravnica: Clue Edition Front Cards", order: 881 },
  pss4: { count: 5, name: "MKM Standard Showdown", order: 880 },
  amkm: { count: 49, name: "Murders at Karlov Manor Art Series", order: 879 },
  pmkm: { count: 180, name: "Murders at Karlov Manor Promos", order: 878 },
  tmkc: {
    count: 31,
    name: "Murders at Karlov Manor Commander Tokens",
    order: 877,
  },
  tmkm: { count: 21, name: "Murders at Karlov Manor Tokens", order: 876 },
  wmkm: { count: 4, name: "MKM Japanese Promo Tokens", order: 875 },
  mkm: { count: 450, name: "Murders at Karlov Manor", order: 874 },
  mkc: { count: 358, name: "Murders at Karlov Manor Commander", order: 873 },
  pl24: { count: 7, name: "Year of the Dragon 2024", order: 872 },
  trvr: { count: 20, name: "Ravnica Remastered Tokens", order: 871 },
  rvr: { count: 531, name: "Ravnica Remastered", order: 870 },
  pf24: { count: 1, name: "MagicFest 2024", order: 869 },
  pw24: { count: 18, name: "Wizards Play Network 2024", order: 868 },
  ylci: { count: 30, name: "Alchemy: Ixalan", order: 867 },
  alci: {
    count: 81,
    name: "The Lost Caverns of Ixalan Art Series",
    order: 866,
  },
  spg: { count: 89, name: "Special Guests", order: 865 },
  plci: { count: 136, name: "The Lost Caverns of Ixalan Promos", order: 864 },
  trex: { count: 2, name: "Jurassic World Collection Tokens", order: 863 },
  tlci: { count: 20, name: "The Lost Caverns of Ixalan Tokens", order: 862 },
  pmat: {
    count: 8,
    name: "March of the Machine: The Aftermath Promos",
    order: 861,
  },
  rex: { count: 45, name: "Jurassic World Collection", order: 860 },
  tlcc: {
    count: 18,
    name: "The Lost Caverns of Ixalan Commander Tokens",
    order: 859,
  },
  lcc: { count: 370, name: "The Lost Caverns of Ixalan Commander", order: 858 },
  slci: {
    count: 1,
    name: "The Lost Caverns of Ixalan Substitute Cards",
    order: 857,
  },
  lci: { count: 416, name: "The Lost Caverns of Ixalan", order: 856 },
  who: { count: 1178, name: "Doctor Who", order: 855 },
  twho: { count: 64, name: "Doctor Who Tokens", order: 854 },
  ywoe: { count: 30, name: "Alchemy: Wilds of Eldraine", order: 853 },
  pwoe: { count: 160, name: "Wilds of Eldraine Promos", order: 852 },
  wot: { count: 103, name: "Wilds of Eldraine: Enchanting Tales", order: 851 },
  woc: { count: 173, name: "Wilds of Eldraine Commander", order: 850 },
  awoe: { count: 81, name: "Wilds of Eldraine Art Series", order: 849 },
  wwoe: { count: 6, name: "WOE Japanese Promo Tokens", order: 848 },
  twoc: { count: 17, name: "Wilds of Eldraine Commander Tokens", order: 847 },
  twoe: { count: 18, name: "Wilds of Eldraine Tokens", order: 846 },
  ptsr: { count: 3, name: "Time Spiral Remastered Promos", order: 845 },
  pmda: { count: 4, name: "Magic × Duel Masters Promos", order: 844 },
  woe: { count: 381, name: "Wilds of Eldraine", order: 843 },
  p30t: { count: 2, name: "30th Anniversary Celebration Tokyo", order: 842 },
  acmm: { count: 81, name: "Commander Masters Art Series", order: 841 },
  tcmm: { count: 81, name: "Commander Masters Tokens", order: 840 },
  cmm: { count: 1067, name: "Commander Masters", order: 839 },
  ph22: { count: 5, name: "2022 Heroes of the Realm", order: 838 },
  ea3: { count: 25, name: "Explorer Anthology 3", order: 837 },
  ha7: { count: 25, name: "Historic Anthology 7", order: 836 },
  pf23: { count: 4, name: "MagicFest 2023", order: 835 },
  pltr: { count: 86, name: "Tales of Middle-earth Promos", order: 834 },
  ltc: { count: 591, name: "Tales of Middle-earth Commander", order: 833 },
  fltr: { count: 10, name: "Tales of Middle-earth Front Cards", order: 832 },
  altr: { count: 81, name: "Tales of Middle-earth Art Series", order: 831 },
  tltr: { count: 25, name: "Tales of Middle-earth Tokens", order: 830 },
  ltr: {
    count: 856,
    name: "The Lord of the Rings: Tales of Middle-earth",
    order: 829,
  },
  tltc: {
    count: 15,
    name: "Tales of Middle-earth Commander Tokens",
    order: 828,
  },
  mat: { count: 230, name: "March of the Machine: The Aftermath", order: 827 },
  fmom: {
    count: 5,
    name: "March of the Machine Jumpstart Front Cards",
    order: 826,
  },
  tmoc: {
    count: 46,
    name: "March of the Machine Commander Tokens",
    order: 825,
  },
  tmul: { count: 2, name: "Multiverse Legends Tokens", order: 824 },
  mom: { count: 387, name: "March of the Machine", order: 823 },
  pmom: { count: 134, name: "March of the Machine Promos", order: 822 },
  smom: { count: 1, name: "March of the Machine Substitute Cards", order: 821 },
  wmom: { count: 12, name: "MOM Japanese Promo Tokens", order: 820 },
  amom: { count: 81, name: "March of the Machine Art Series", order: 819 },
  mul: { count: 261, name: "Multiverse Legends", order: 818 },
  tmom: { count: 23, name: "March of the Machine Tokens", order: 817 },
  moc: { count: 450, name: "March of the Machine Commander", order: 816 },
  sis: { count: 76, name: "Shadows of the Past", order: 815 },
  sir: { count: 294, name: "Shadows over Innistrad Remastered", order: 814 },
  yone: { count: 30, name: "Alchemy: Phyrexia", order: 813 },
  slp: { count: 34, name: "Secret Lair Showdown", order: 812 },
  da1: { count: 368, name: "Unknown Event", order: 811 },
  pl23: { count: 6, name: "Year of the Rabbit 2023", order: 810 },
  pone: { count: 160, name: "Phyrexia: All Will Be One Promos", order: 809 },
  tonc: {
    count: 23,
    name: "Phyrexia: All Will Be One Commander Tokens",
    order: 808,
  },
  tone: { count: 14, name: "Phyrexia: All Will Be One Tokens", order: 807 },
  fone: {
    count: 5,
    name: "Phyrexia: All Will Be One Jumpstart Front Cards",
    order: 806,
  },
  aone: { count: 81, name: "Phyrexia: All Will Be One Art Series", order: 805 },
  onc: { count: 174, name: "Phyrexia: All Will Be One Commander", order: 804 },
  mone: { count: 5, name: "Phyrexia: All Will Be One Minigames", order: 803 },
  one: { count: 479, name: "Phyrexia: All Will Be One", order: 802 },
  wone: { count: 6, name: "ONE Japanese Promo Tokens", order: 801 },
  dmr: { count: 457, name: "Dominaria Remastered", order: 800 },
  tdmr: { count: 14, name: "Dominaria Remastered Tokens", order: 799 },
  pr23: { count: 3, name: "Regional Championship Qualifiers 2023", order: 798 },
  pw23: { count: 11, name: "Wizards Play Network 2023", order: 797 },
  p23: { count: 10, name: "Judge Gift Cards 2023", order: 796 },
  ybro: { count: 31, name: "Alchemy: The Brothers' War", order: 795 },
  ea2: { count: 25, name: "Explorer Anthology 2", order: 794 },
  tscd: { count: 27, name: "Starter Commander Deck Tokens", order: 793 },
  scd: { count: 352, name: "Starter Commander Decks", order: 792 },
  fj22: { count: 46, name: "Jumpstart 2022 Front Cards", order: 791 },
  j22: { count: 835, name: "Jumpstart 2022", order: 790 },
  "30a": { count: 594, name: "30th Anniversary Edition", order: 789 },
  t30a: { count: 16, name: "30th Anniversary Tokens", order: 788 },
  pewk: { count: 6, name: "Eternal Weekend", order: 787 },
  brc: { count: 209, name: "The Brothers' War Commander", order: 786 },
  brr: { count: 189, name: "The Brothers' War Retro Artifacts", order: 785 },
  pbro: { count: 171, name: "The Brothers' War Promos", order: 784 },
  tbot: { count: 2, name: "Transformers Tokens", order: 783 },
  bot: { count: 29, name: "Transformers", order: 782 },
  ptbro: {
    count: 3,
    name: "The Brothers' War Southeast Asia Tokens",
    order: 781,
  },
  tbrc: { count: 14, name: "The Brothers' War Commander Tokens", order: 780 },
  mbro: { count: 3, name: "The Brothers' War Minigames", order: 779 },
  tbro: { count: 12, name: "The Brothers' War Tokens", order: 778 },
  abro: { count: 81, name: "The Brothers' War Art Series", order: 777 },
  fbro: {
    count: 5,
    name: "The Brothers' War Jumpstart Front Cards",
    order: 776,
  },
  sbro: { count: 1, name: "The Brothers' War Substitute Cards", order: 775 },
  bro: { count: 399, name: "The Brothers' War", order: 774 },
  slc: {
    count: 31,
    name: "Secret Lair 30th Anniversary Countdown Kit",
    order: 773,
  },
  tgn3: { count: 10, name: "Game Night: Free-for-All Tokens", order: 772 },
  gn3: { count: 135, name: "Game Night: Free-for-All", order: 771 },
  ulst: { count: 62, name: "The List (Unfinity Foil Edition)", order: 770 },
  sunf: { count: 48, name: "Unfinity Sticker Sheets", order: 769 },
  unf: { count: 639, name: "Unfinity", order: 768 },
  tunf: { count: 14, name: "Unfinity Tokens", order: 767 },
  "40k": { count: 618, name: "Warhammer 40,000 Commander", order: 766 },
  t40k: { count: 31, name: "Warhammer 40,000 Tokens", order: 765 },
  ydmu: { count: 39, name: "Alchemy: Dominaria", order: 764 },
  prcq: { count: 3, name: "Regional Championship Qualifiers 2022", order: 763 },
  p30h: { count: 10, name: "30th Anniversary History Promos", order: 762 },
  pdmu: { count: 161, name: "Dominaria United Promos", order: 761 },
  ptdmu: {
    count: 3,
    name: "Dominaria United Southeast Asia Tokens",
    order: 760,
  },
  admu: { count: 81, name: "Dominaria United Art Series", order: 759 },
  mdmu: { count: 3, name: "Dominaria United Minigames", order: 758 },
  dmc: { count: 240, name: "Dominaria United Commander", order: 757 },
  tdmc: { count: 12, name: "Dominaria United Commander Tokens", order: 756 },
  dmu: { count: 453, name: "Dominaria United", order: 755 },
  wdmu: { count: 5, name: "DMU Japanese Promo Tokens", order: 754 },
  fdmu: {
    count: 10,
    name: "Dominaria United Jumpstart Front Cards",
    order: 753,
  },
  tdmu: { count: 26, name: "Dominaria United Tokens", order: 752 },
  p30a: { count: 30, name: "30th Anniversary Play Promos", order: 751 },
  p30m: { count: 5, name: "30th Anniversary Misc Promos", order: 750 },
  psvc: { count: 3, name: "Summer Vacation Promos 2022", order: 749 },
  ph21: { count: 4, name: "2021 Heroes of the Realm", order: 748 },
  ea1: { count: 20, name: "Explorer Anthology 1", order: 747 },
  ha6: { count: 20, name: "Historic Anthology 6", order: 746 },
  sch: { count: 32, name: "Store Championships", order: 745 },
  t2x2: { count: 24, name: "Double Masters 2022 Tokens", order: 744 },
  "2x2": { count: 579, name: "Double Masters 2022", order: 743 },
  hbg: { count: 436, name: "Alchemy Horizons: Baldur's Gate", order: 742 },
  plg22: { count: 2, name: "Love Your LGS 2022", order: 741 },
  pclb: { count: 104, name: "Battle for Baldur's Gate Promos", order: 740 },
  mclb: {
    count: 3,
    name: "Commander Legends: Battle for Baldur's Gate Minigames",
    order: 739,
  },
  tclb: { count: 51, name: "Battle for Baldur's Gate Tokens", order: 738 },
  aclb: { count: 81, name: "Battle for Baldur's Gate Art Series", order: 737 },
  clb: {
    count: 936,
    name: "Commander Legends: Battle for Baldur's Gate",
    order: 736,
  },
  ysnc: { count: 30, name: "Alchemy: New Capenna", order: 735 },
  ptsnc: {
    count: 6,
    name: "Streets of New Capenna Southeast Asia Tokens",
    order: 734,
  },
  pncc: { count: 75, name: "New Capenna Commander Promos", order: 733 },
  tsnc: { count: 17, name: "Streets of New Capenna Tokens", order: 732 },
  snc: { count: 513, name: "Streets of New Capenna", order: 731 },
  ncc: { count: 447, name: "New Capenna Commander", order: 730 },
  psnc: { count: 161, name: "Streets of New Capenna Promos", order: 729 },
  msnc: { count: 3, name: "Streets of New Capenna Minigames", order: 728 },
  asnc: { count: 81, name: "New Capenna Art Series", order: 727 },
  tncc: { count: 36, name: "New Capenna Commander Tokens", order: 726 },
  gdy: { count: 9, name: "Game Day Promos", order: 725 },
  q07: { count: 1, name: "Challenger Decks 2022", order: 724 },
  yneo: { count: 30, name: "Alchemy: Kamigawa", order: 723 },
  pw22: { count: 6, name: "Wizards Play Network 2022", order: 722 },
  slx: { count: 23, name: "Universes Within", order: 721 },
  pl22: { count: 5, name: "Year of the Tiger 2022", order: 720 },
  pneo: { count: 148, name: "Kamigawa: Neon Dynasty Promos", order: 719 },
  mneo: { count: 3, name: "Kamigawa: Neon Dynasty Minigames", order: 718 },
  sneo: {
    count: 9,
    name: "Kamigawa: Neon Dynasty Substitute Cards",
    order: 717,
  },
  tneo: { count: 19, name: "Kamigawa: Neon Dynasty Tokens", order: 716 },
  tnec: { count: 12, name: "Neon Dynasty Commander Tokens", order: 715 },
  neo: { count: 531, name: "Kamigawa: Neon Dynasty", order: 714 },
  nec: { count: 179, name: "Neon Dynasty Commander", order: 713 },
  aneo: { count: 81, name: "Neon Dynasty Art Series", order: 712 },
  cc2: { count: 9, name: "Commander Collection: Black", order: 711 },
  dbl: { count: 535, name: "Innistrad: Double Feature", order: 710 },
  p22: { count: 10, name: "Judge Gift Cards 2022", order: 709 },
  ymid: { count: 63, name: "Alchemy: Innistrad", order: 708 },
  pvow: { count: 114, name: "Innistrad: Crimson Vow Promos", order: 707 },
  tvow: { count: 21, name: "Innistrad: Crimson Vow Tokens", order: 706 },
  ovoc: {
    count: 2,
    name: "Crimson Vow Commander Display Commanders",
    order: 705,
  },
  tvoc: { count: 6, name: "Crimson Vow Commander Tokens", order: 704 },
  mvow: { count: 3, name: "Innistrad: Crimson Vow Minigames", order: 703 },
  svow: {
    count: 9,
    name: "Innistrad: Crimson Vow Substitute Cards",
    order: 702,
  },
  avow: { count: 81, name: "Crimson Vow Art Series", order: 701 },
  voc: { count: 188, name: "Crimson Vow Commander", order: 700 },
  vow: { count: 423, name: "Innistrad: Crimson Vow", order: 699 },
  q06: { count: 10, name: "Pioneer Challenger Decks 2021", order: 698 },
  smid: {
    count: 9,
    name: "Innistrad: Midnight Hunt Substitute Cards",
    order: 697,
  },
  tmic: { count: 11, name: "Midnight Hunt Commander Tokens", order: 696 },
  mic: { count: 187, name: "Midnight Hunt Commander", order: 695 },
  pmid: { count: 155, name: "Innistrad: Midnight Hunt Promos", order: 694 },
  amid: { count: 81, name: "Midnight Hunt Art Series", order: 693 },
  omic: {
    count: 2,
    name: "Midnight Hunt Commander Display Commanders",
    order: 692,
  },
  tmid: { count: 19, name: "Innistrad: Midnight Hunt Tokens", order: 691 },
  mmid: { count: 3, name: "Innistrad: Midnight Hunt Minigames", order: 690 },
  mid: { count: 400, name: "Innistrad: Midnight Hunt", order: 689 },
  j21: { count: 389, name: "Jumpstart: Historic Horizons", order: 688 },
  cmb2: { count: 121, name: "Mystery Booster Playtest Cards 2021", order: 687 },
  ph20: { count: 3, name: "2020 Heroes of the Realm", order: 686 },
  pafr: {
    count: 240,
    name: "Adventures in the Forgotten Realms Promos",
    order: 685,
  },
  oafc: {
    count: 4,
    name: "Forgotten Realms Commander Display Commanders",
    order: 684,
  },
  aafr: {
    count: 81,
    name: "Adventures in the Forgotten Realms Art Series",
    order: 683,
  },
  afc: { count: 331, name: "Forgotten Realms Commander", order: 682 },
  tafc: { count: 13, name: "Forgotten Realms Commander Tokens", order: 681 },
  tafr: {
    count: 22,
    name: "Adventures in the Forgotten Realms Tokens",
    order: 680,
  },
  mafr: {
    count: 5,
    name: "Adventures in the Forgotten Realms Minigames",
    order: 679,
  },
  afr: { count: 424, name: "Adventures in the Forgotten Realms", order: 678 },
  plg21: { count: 11, name: "Love Your LGS 2021", order: 677 },
  pmh2: { count: 86, name: "Modern Horizons 2 Promos", order: 676 },
  amh2: { count: 162, name: "Modern Horizons 2 Art Series", order: 675 },
  tmh2: { count: 21, name: "Modern Horizons 2 Tokens", order: 674 },
  mmh2: { count: 5, name: "Modern Horizons 2 Minigames", order: 673 },
  pw21: { count: 6, name: "Wizards Play Network 2021", order: 672 },
  h1r: { count: 40, name: "Modern Horizons 1 Timeshifts", order: 671 },
  mh2: { count: 494, name: "Modern Horizons 2", order: 670 },
  ha5: { count: 25, name: "Historic Anthology 5", order: 669 },
  pstx: { count: 164, name: "Strixhaven: School of Mages Promos", order: 668 },
  tstx: { count: 9, name: "Strixhaven: School of Mages Tokens", order: 667 },
  tc21: { count: 30, name: "Commander 2021 Tokens", order: 666 },
  sstx: {
    count: 9,
    name: "Strixhaven: School of Mages Substitute Cards",
    order: 665,
  },
  mstx: { count: 5, name: "Strixhaven: School of Mages Minigames", order: 664 },
  oc21: { count: 5, name: "Commander 2021 Display Commanders", order: 663 },
  astx: { count: 162, name: "Strixhaven Art Series", order: 662 },
  stx: { count: 393, name: "Strixhaven: School of Mages", order: 661 },
  c21: { count: 409, name: "Commander 2021", order: 660 },
  sta: { count: 126, name: "Strixhaven Mystical Archive", order: 659 },
  ttsr: { count: 15, name: "Time Spiral Remastered Tokens", order: 658 },
  tsr: { count: 411, name: "Time Spiral Remastered", order: 657 },
  ha4: { count: 25, name: "Historic Anthology 4", order: 656 },
  pkhm: { count: 158, name: "Kaldheim Promos", order: 655 },
  mkhm: { count: 5, name: "Kaldheim Minigames", order: 654 },
  skhm: { count: 9, name: "Kaldheim Substitute Cards", order: 653 },
  tkhm: { count: 23, name: "Kaldheim Tokens", order: 652 },
  khc: { count: 119, name: "Kaldheim Commander", order: 651 },
  khm: { count: 426, name: "Kaldheim", order: 650 },
  tkhc: { count: 8, name: "Kaldheim Commander Tokens", order: 649 },
  akhm: { count: 81, name: "Kaldheim Art Series", order: 648 },
  pl21: { count: 6, name: "Year of the Ox 2021", order: 647 },
  pj21: { count: 10, name: "Judge Gift Cards 2021", order: 646 },
  cc1: { count: 8, name: "Commander Collection: Green", order: 645 },
  pcmr: { count: 6, name: "Commander Legends Promos", order: 644 },
  cmr: { count: 718, name: "Commander Legends", order: 643 },
  tcmr: { count: 23, name: "Commander Legends Tokens", order: 642 },
  klr: { count: 302, name: "Kaladesh Remastered", order: 641 },
  plst: { count: 4809, name: "The List", order: 640 },
  pznr: { count: 153, name: "Zendikar Rising Promos", order: 639 },
  tznc: { count: 11, name: "Zendikar Rising Commander Tokens", order: 638 },
  tznr: { count: 12, name: "Zendikar Rising Tokens", order: 637 },
  zne: { count: 30, name: "Zendikar Rising Expeditions", order: 636 },
  znc: { count: 142, name: "Zendikar Rising Commander", order: 635 },
  znr: { count: 408, name: "Zendikar Rising", order: 634 },
  mznr: { count: 5, name: "Zendikar Rising Minigames", order: 633 },
  aznr: { count: 81, name: "Zendikar Rising Art Series", order: 632 },
  sznr: { count: 9, name: "Zendikar Rising Substitute Cards", order: 631 },
  akr: { count: 339, name: "Amonkhet Remastered", order: 630 },
  anb: { count: 120, name: "Arena Beginner Set", order: 629 },
  "2xm": { count: 384, name: "Double Masters", order: 628 },
  t2xm: { count: 31, name: "Double Masters Tokens", order: 627 },
  ph19: { count: 7, name: "2019 Heroes of the Realm", order: 626 },
  ajmp: { count: 18, name: "Jumpstart Arena Exclusives", order: 625 },
  jmp: { count: 497, name: "Jumpstart", order: 624 },
  pm21: { count: 137, name: "Core Set 2021 Promos", order: 623 },
  tm21: { count: 20, name: "Core Set 2021 Tokens", order: 622 },
  m21: { count: 397, name: "Core Set 2021", order: 621 },
  ss3: { count: 8, name: "Signature Spellbook: Chandra", order: 620 },
  fjmp: { count: 46, name: "Jumpstart Front Cards", order: 619 },
  slu: { count: 16, name: "Secret Lair: Ultimate Edition", order: 618 },
  ha3: { count: 27, name: "Historic Anthology 3", order: 617 },
  plg20: { count: 2, name: "Love Your LGS 2020", order: 616 },
  piko: { count: 137, name: "Ikoria: Lair of Behemoths Promos", order: 615 },
  iko: { count: 390, name: "Ikoria: Lair of Behemoths", order: 614 },
  tiko: { count: 15, name: "Ikoria: Lair of Behemoths Tokens", order: 613 },
  oc20: { count: 5, name: "Commander 2020 Oversized", order: 612 },
  tc20: { count: 21, name: "Commander 2020 Tokens", order: 611 },
  c20: { count: 322, name: "Commander 2020", order: 610 },
  ha2: { count: 25, name: "Historic Anthology 2", order: 609 },
  tund: { count: 6, name: "Unsanctioned Tokens", order: 608 },
  und: { count: 96, name: "Unsanctioned", order: 607 },
  pthb: { count: 137, name: "Theros Beyond Death Promos", order: 606 },
  tthb: { count: 14, name: "Theros Beyond Death Tokens", order: 605 },
  thb: { count: 358, name: "Theros Beyond Death", order: 604 },
  j20: { count: 10, name: "Judge Gift Cards 2020", order: 603 },
  pf20: { count: 6, name: "MagicFest 2020", order: 602 },
  sld: { count: 1709, name: "Secret Lair Drop", order: 601 },
  ha1: { count: 20, name: "Historic Anthology 1", order: 600 },
  tgn2: { count: 3, name: "Game Night 2019 Tokens", order: 599 },
  gn2: { count: 64, name: "Game Night 2019", order: 598 },
  cmb1: { count: 121, name: "Mystery Booster Playtest Cards 2019", order: 597 },
  ptg: { count: 3, name: "Ponies: The Galloping", order: 596 },
  peld: { count: 138, name: "Throne of Eldraine Promos", order: 595 },
  eld: { count: 399, name: "Throne of Eldraine", order: 594 },
  pwcs: { count: 32, name: "Planeswalker Championship Promos", order: 593 },
  teld: { count: 20, name: "Throne of Eldraine Tokens", order: 592 },
  oc19: { count: 4, name: "Commander 2019 Oversized", order: 591 },
  c19: { count: 302, name: "Commander 2019", order: 590 },
  tc19: { count: 29, name: "Commander 2019 Tokens", order: 589 },
  ph18: { count: 5, name: "2018 Heroes of the Realm", order: 588 },
  ps19: { count: 5, name: "San Diego Comic-Con 2019", order: 587 },
  pm20: { count: 144, name: "Core Set 2020 Promos", order: 586 },
  tm20: { count: 12, name: "Core Set 2020 Tokens", order: 585 },
  ppp1: { count: 5, name: "M20 Promo Packs", order: 584 },
  m20: { count: 345, name: "Core Set 2020", order: 583 },
  ss2: { count: 8, name: "Signature Spellbook: Gideon", order: 582 },
  pmh1: { count: 2, name: "Modern Horizons Promos", order: 581 },
  mh1: { count: 255, name: "Modern Horizons", order: 580 },
  amh1: { count: 54, name: "Modern Horizons Art Series", order: 579 },
  tmh1: { count: 21, name: "Modern Horizons Tokens", order: 578 },
  pwar: { count: 176, name: "War of the Spark Promos", order: 577 },
  twar: { count: 19, name: "War of the Spark Tokens", order: 576 },
  war: { count: 312, name: "War of the Spark", order: 575 },
  j19: { count: 8, name: "Judge Gift Cards 2019", order: 574 },
  prw2: { count: 10, name: "RNA Ravnica Weekend", order: 573 },
  gk2: { count: 133, name: "RNA Guild Kit", order: 572 },
  tgk2: { count: 9, name: "RNA Guild Kit Tokens", order: 571 },
  prna: { count: 81, name: "Ravnica Allegiance Promos", order: 570 },
  trna: { count: 13, name: "Ravnica Allegiance Tokens", order: 569 },
  rna: { count: 273, name: "Ravnica Allegiance", order: 568 },
  pf19: { count: 7, name: "MagicFest 2019", order: 567 },
  opca: { count: 86, name: "Planechase Anthology Planes", order: 566 },
  puma: { count: 40, name: "Ultimate Box Topper", order: 565 },
  tuma: { count: 16, name: "Ultimate Masters Tokens", order: 564 },
  uma: { count: 254, name: "Ultimate Masters", order: 563 },
  gnt: { count: 68, name: "Game Night", order: 562 },
  g18: { count: 5, name: "M19 Gift Pack", order: 561 },
  prwk: { count: 10, name: "GRN Ravnica Weekend", order: 560 },
  gk1: { count: 127, name: "GRN Guild Kit", order: 559 },
  tgk1: { count: 10, name: "GRN Guild Kit Tokens", order: 558 },
  pgrn: { count: 84, name: "Guilds of Ravnica Promos", order: 557 },
  tgrn: { count: 8, name: "Guilds of Ravnica Tokens", order: 556 },
  grn: { count: 273, name: "Guilds of Ravnica", order: 555 },
  med: { count: 24, name: "Mythic Edition", order: 554 },
  tmed: { count: 16, name: "Mythic Edition Tokens", order: 553 },
  oc18: { count: 4, name: "Commander 2018 Oversized", order: 552 },
  tc18: { count: 26, name: "Commander 2018 Tokens", order: 551 },
  c18: { count: 307, name: "Commander 2018", order: 550 },
  ph17: { count: 3, name: "2017 Heroes of the Realm", order: 549 },
  ps18: { count: 5, name: "San Diego Comic-Con 2018", order: 548 },
  xana: { count: 20, name: "Arena New Player Experience Extras", order: 547 },
  ana: { count: 40, name: "Arena New Player Experience", order: 546 },
  pana: { count: 78, name: "MTG Arena Promos", order: 545 },
  oana: { count: 14, name: "Arena New Player Experience Cards", order: 544 },
  pm19: { count: 95, name: "Core Set 2019 Promos", order: 543 },
  pss3: { count: 5, name: "M19 Standard Showdown", order: 542 },
  tm19: { count: 18, name: "Core Set 2019 Tokens", order: 541 },
  m19: { count: 314, name: "Core Set 2019", order: 540 },
  gs1: {
    count: 41,
    name: "Global Series Jiang Yanggu & Mu Yanling",
    order: 539,
  },
  ss1: { count: 8, name: "Signature Spellbook: Jace", order: 538 },
  pbbd: { count: 22, name: "Battlebond Promos", order: 537 },
  tbbd: { count: 8, name: "Battlebond Tokens", order: 536 },
  tcm2: { count: 19, name: "Commander Anthology Volume II Tokens", order: 535 },
  bbd: { count: 256, name: "Battlebond", order: 534 },
  cm2: { count: 312, name: "Commander Anthology Volume II", order: 533 },
  pdom: { count: 118, name: "Dominaria Promos", order: 532 },
  dom: { count: 280, name: "Dominaria", order: 531 },
  tdom: { count: 16, name: "Dominaria Tokens", order: 530 },
  ddu: { count: 76, name: "Duel Decks: Elves vs. Inventors", order: 529 },
  tddu: {
    count: 4,
    name: "Duel Decks: Elves vs. Inventors Tokens",
    order: 528,
  },
  a25: { count: 249, name: "Masters 25", order: 527 },
  ta25: { count: 16, name: "Masters 25 Tokens", order: 526 },
  plny: { count: 1, name: "Lunar New Year 2018 ", order: 525 },
  pnat: { count: 1, name: "Nationals Promos", order: 524 },
  prix: { count: 98, name: "Rivals of Ixalan Promos", order: 523 },
  trix: { count: 7, name: "Rivals of Ixalan Tokens", order: 522 },
  rix: { count: 205, name: "Rivals of Ixalan", order: 521 },
  j18: { count: 8, name: "Judge Gift Cards 2018", order: 520 },
  f18: { count: 3, name: "Friday Night Magic 2018", order: 519 },
  pust: { count: 1, name: "Unstable Promos", order: 518 },
  tust: { count: 20, name: "Unstable Tokens", order: 517 },
  ust: { count: 268, name: "Unstable", order: 516 },
  tima: { count: 7, name: "Iconic Masters Tokens", order: 515 },
  pxtc: { count: 10, name: "XLN Treasure Chest", order: 514 },
  v17: { count: 16, name: "From the Vault: Transform", order: 513 },
  e02: { count: 48, name: "Explorers of Ixalan", order: 512 },
  ima: { count: 249, name: "Iconic Masters", order: 511 },
  ddt: { count: 63, name: "Duel Decks: Merfolk vs. Goblins", order: 510 },
  tddt: {
    count: 3,
    name: "Duel Decks: Merfolk vs. Goblins Tokens",
    order: 509,
  },
  g17: { count: 5, name: "2017 Gift Pack", order: 508 },
  pxln: { count: 120, name: "Ixalan Promos", order: 507 },
  xln: { count: 289, name: "Ixalan", order: 506 },
  txln: { count: 11, name: "Ixalan Tokens", order: 505 },
  pss2: { count: 5, name: "XLN Standard Showdown", order: 504 },
  h17: { count: 4, name: "HasCon 2017", order: 503 },
  phtr: { count: 3, name: "2016 Heroes of the Realm", order: 502 },
  te01: { count: 5, name: "Archenemy: Nicol Bolas Tokens", order: 501 },
  oc17: { count: 4, name: "Commander 2017 Oversized", order: 500 },
  c17: { count: 309, name: "Commander 2017", order: 499 },
  tc17: { count: 11, name: "Commander 2017 Tokens", order: 498 },
  ps17: { count: 6, name: "San Diego Comic-Con 2017", order: 497 },
  phou: { count: 62, name: "Hour of Devastation Promos", order: 496 },
  hou: { count: 209, name: "Hour of Devastation", order: 495 },
  thou: { count: 14, name: "Hour of Devastation Tokens", order: 494 },
  oe01: { count: 20, name: "Archenemy: Nicol Bolas Schemes", order: 493 },
  e01: { count: 106, name: "Archenemy: Nicol Bolas", order: 492 },
  tcma: { count: 20, name: "Commander Anthology Tokens", order: 491 },
  cma: { count: 320, name: "Commander Anthology", order: 490 },
  pakh: { count: 77, name: "Amonkhet Promos", order: 489 },
  akh: { count: 287, name: "Amonkhet", order: 488 },
  takh: { count: 27, name: "Amonkhet Tokens", order: 487 },
  mp2: { count: 54, name: "Amonkhet Invocations", order: 486 },
  w17: { count: 30, name: "Welcome Deck 2017", order: 485 },
  dds: { count: 65, name: "Duel Decks: Mind vs. Might", order: 484 },
  tdds: { count: 7, name: "Duel Decks: Mind vs. Might Tokens", order: 483 },
  mm3: { count: 249, name: "Modern Masters 2017", order: 482 },
  tmm3: { count: 21, name: "Modern Masters 2017 Tokens", order: 481 },
  paer: { count: 65, name: "Aether Revolt Promos", order: 480 },
  taer: { count: 4, name: "Aether Revolt Tokens", order: 479 },
  aer: { count: 197, name: "Aether Revolt", order: 478 },
  l17: { count: 1, name: "League Tokens 2017", order: 477 },
  f17: { count: 12, name: "Friday Night Magic 2017", order: 476 },
  j17: { count: 9, name: "Judge Gift Cards 2017", order: 475 },
  tpca: { count: 19, name: "Planechase Anthology Tokens", order: 474 },
  pca: { count: 156, name: "Planechase Anthology", order: 473 },
  pz2: { count: 282, name: "Treasure Chest", order: 472 },
  oc16: { count: 5, name: "Commander 2016 Oversized", order: 471 },
  tc16: { count: 21, name: "Commander 2016 Tokens", order: 470 },
  c16: { count: 351, name: "Commander 2016", order: 469 },
  ps16: { count: 5, name: "San Diego Comic-Con 2016", order: 468 },
  pkld: { count: 83, name: "Kaladesh Promos", order: 467 },
  kld: { count: 278, name: "Kaladesh", order: 466 },
  tkld: { count: 13, name: "Kaladesh Tokens", order: 465 },
  mps: { count: 54, name: "Kaladesh Inventions", order: 464 },
  ddr: { count: 76, name: "Duel Decks: Nissa vs. Ob Nixilis", order: 463 },
  cn2: { count: 222, name: "Conspiracy: Take the Crown", order: 462 },
  tcn2: { count: 12, name: "Conspiracy: Take the Crown Tokens", order: 461 },
  v16: { count: 16, name: "From the Vault: Lore", order: 460 },
  pemn: { count: 77, name: "Eldritch Moon Promos", order: 459 },
  emn: { count: 208, name: "Eldritch Moon", order: 458 },
  temn: { count: 11, name: "Eldritch Moon Tokens", order: 457 },
  tema: { count: 16, name: "Eternal Masters Tokens", order: 456 },
  ema: { count: 249, name: "Eternal Masters", order: 455 },
  psoi: { count: 90, name: "Shadows over Innistrad Promos", order: 454 },
  tsoi: { count: 20, name: "Shadows over Innistrad Tokens", order: 453 },
  w16: { count: 16, name: "Welcome Deck 2016", order: 452 },
  soi: { count: 302, name: "Shadows over Innistrad", order: 451 },
  ddq: { count: 80, name: "Duel Decks: Blessed vs. Cursed", order: 450 },
  togw: { count: 11, name: "Oath of the Gatewatch Tokens", order: 449 },
  ogw: { count: 187, name: "Oath of the Gatewatch", order: 448 },
  pogw: { count: 65, name: "Oath of the Gatewatch Promos", order: 447 },
  l16: { count: 1, name: "League Tokens 2016", order: 446 },
  j16: { count: 8, name: "Judge Gift Cards 2016", order: 445 },
  f16: { count: 12, name: "Friday Night Magic 2016", order: 444 },
  pz1: { count: 149, name: "Legendary Cube Prize Pack", order: 443 },
  oc15: { count: 5, name: "Commander 2015 Oversized", order: 442 },
  tc15: { count: 25, name: "Commander 2015 Tokens", order: 441 },
  c15: { count: 342, name: "Commander 2015", order: 440 },
  tbfz: { count: 14, name: "Battle for Zendikar Tokens", order: 439 },
  pbfz: { count: 90, name: "Battle for Zendikar Promos", order: 438 },
  bfz: { count: 299, name: "Battle for Zendikar", order: 437 },
  pss1: { count: 5, name: "BFZ Standard Series", order: 436 },
  exp: { count: 45, name: "Zendikar Expeditions", order: 435 },
  ddp: { count: 80, name: "Duel Decks: Zendikar vs. Eldrazi", order: 434 },
  v15: { count: 15, name: "From the Vault: Angels", order: 433 },
  cp3: { count: 6, name: "Magic Origins Clash Pack", order: 432 },
  pori: { count: 54, name: "Magic Origins Promos", order: 431 },
  tori: { count: 15, name: "Magic Origins Tokens", order: 430 },
  ori: { count: 288, name: "Magic Origins", order: 429 },
  ps15: { count: 5, name: "San Diego Comic-Con 2015", order: 428 },
  mm2: { count: 249, name: "Modern Masters 2015", order: 427 },
  tmm2: { count: 16, name: "Modern Masters 2015 Tokens", order: 426 },
  tpr: { count: 269, name: "Tempest Remastered", order: 425 },
  ptkdf: { count: 4, name: "Tarkir Dragonfury", order: 424 },
  pdtk: { count: 51, name: "Dragons of Tarkir Promos", order: 423 },
  tdtk: { count: 8, name: "Dragons of Tarkir Tokens", order: 422 },
  dtk: { count: 264, name: "Dragons of Tarkir", order: 421 },
  ddo: { count: 67, name: "Duel Decks: Elspeth vs. Kiora", order: 420 },
  pfrf: { count: 43, name: "Fate Reforged Promos", order: 419 },
  cp2: { count: 6, name: "Fate Reforged Clash Pack", order: 418 },
  frf: { count: 191, name: "Fate Reforged", order: 417 },
  tfrf: { count: 4, name: "Fate Reforged Tokens", order: 416 },
  ugin: { count: 26, name: "Ugin's Fate", order: 415 },
  l15: { count: 1, name: "League Tokens 2015", order: 414 },
  f15: { count: 12, name: "Friday Night Magic 2015", order: 413 },
  j15: { count: 8, name: "Judge Gift Cards 2015", order: 412 },
  tjvc: {
    count: 1,
    name: "Duel Decks Anthology: Jace vs. Chandra Tokens",
    order: 411,
  },
  tdvd: {
    count: 3,
    name: "Duel Decks Anthology: Divine vs. Demonic Tokens",
    order: 410,
  },
  tgvl: {
    count: 4,
    name: "Duel Decks Anthology: Garruk vs. Liliana Tokens",
    order: 409,
  },
  evg: {
    count: 62,
    name: "Duel Decks Anthology: Elves vs. Goblins",
    order: 408,
  },
  dvd: {
    count: 62,
    name: "Duel Decks Anthology: Divine vs. Demonic",
    order: 407,
  },
  jvc: {
    count: 62,
    name: "Duel Decks Anthology: Jace vs. Chandra",
    order: 406,
  },
  tevg: {
    count: 3,
    name: "Duel Decks Anthology: Elves vs. Goblins Tokens",
    order: 405,
  },
  gvl: {
    count: 63,
    name: "Duel Decks Anthology: Garruk vs. Liliana",
    order: 404,
  },
  oc14: { count: 5, name: "Commander 2014 Oversized", order: 403 },
  tc14: { count: 36, name: "Commander 2014 Tokens", order: 402 },
  c14: { count: 337, name: "Commander 2014", order: 401 },
  pktk: { count: 56, name: "Khans of Tarkir Promos", order: 400 },
  tktk: { count: 13, name: "Khans of Tarkir Tokens", order: 399 },
  ktk: { count: 293, name: "Khans of Tarkir", order: 398 },
  ddn: { count: 82, name: "Duel Decks: Speed vs. Cunning", order: 397 },
  v14: { count: 15, name: "From the Vault: Annihilation", order: 396 },
  m15: { count: 284, name: "Magic 2015", order: 395 },
  tm15: { count: 14, name: "Magic 2015 Tokens", order: 394 },
  cp1: { count: 6, name: "Magic 2015 Clash Pack", order: 393 },
  pm15: { count: 14, name: "Magic 2015 Promos", order: 392 },
  ppc1: { count: 2, name: "M15 Prerelease Challenge", order: 391 },
  pdp15: {
    count: 2,
    name: "Duels of the Planeswalkers 2015 Promos ",
    order: 390,
  },
  ps14: { count: 6, name: "San Diego Comic-Con 2014", order: 389 },
  vma: { count: 325, name: "Vintage Masters", order: 388 },
  pcns: { count: 1, name: "Conspiracy Promos", order: 387 },
  tcns: { count: 9, name: "Conspiracy Tokens", order: 386 },
  cns: { count: 210, name: "Conspiracy", order: 385 },
  tmd1: { count: 4, name: "Modern Event Deck 2014 Tokens", order: 384 },
  md1: { count: 26, name: "Modern Event Deck 2014", order: 383 },
  tdag: { count: 15, name: "Defeat a God", order: 382 },
  thp3: { count: 8, name: "Journey into Nyx Hero's Path", order: 381 },
  tjou: { count: 6, name: "Journey into Nyx Tokens", order: 380 },
  jou: { count: 165, name: "Journey into Nyx", order: 379 },
  pjou: { count: 10, name: "Journey into Nyx Promos", order: 378 },
  tddm: { count: 1, name: "Duel Decks: Jace vs. Vraska Tokens", order: 377 },
  ddm: { count: 88, name: "Duel Decks: Jace vs. Vraska", order: 376 },
  tbth: { count: 15, name: "Battle the Horde", order: 375 },
  bng: { count: 165, name: "Born of the Gods", order: 374 },
  tbng: { count: 11, name: "Born of the Gods Tokens", order: 373 },
  thp2: { count: 7, name: "Born of the Gods Hero's Path", order: 372 },
  pbng: { count: 9, name: "Born of the Gods Promos", order: 371 },
  l14: { count: 4, name: "League Tokens 2014", order: 370 },
  j14: { count: 14, name: "Judge Gift Cards 2014", order: 369 },
  f14: { count: 12, name: "Friday Night Magic 2014", order: 368 },
  oc13: { count: 15, name: "Commander 2013 Oversized", order: 367 },
  c13: { count: 356, name: "Commander 2013", order: 366 },
  tfth: { count: 15, name: "Face the Hydra", order: 365 },
  thp1: { count: 7, name: "Theros Hero's Path", order: 364 },
  tths: { count: 11, name: "Theros Tokens", order: 363 },
  ths: { count: 249, name: "Theros", order: 362 },
  pths: { count: 10, name: "Theros Promos", order: 361 },
  ddl: { count: 81, name: "Duel Decks: Heroes vs. Monsters", order: 360 },
  tddl: {
    count: 2,
    name: "Duel Decks: Heroes vs. Monsters Tokens",
    order: 359,
  },
  v13: { count: 20, name: "From the Vault: Twenty", order: 358 },
  m14: { count: 249, name: "Magic 2014", order: 357 },
  tm14: { count: 13, name: "Magic 2014 Tokens", order: 356 },
  pm14: { count: 6, name: "Magic 2014 Promos", order: 355 },
  psdc: { count: 5, name: "San Diego Comic-Con 2013", order: 354 },
  mma: { count: 229, name: "Modern Masters", order: 353 },
  tmma: { count: 16, name: "Modern Masters Tokens", order: 352 },
  dgm: { count: 156, name: "Dragon's Maze", order: 351 },
  tdgm: { count: 1, name: "Dragon's Maze Tokens", order: 350 },
  pdgm: { count: 6, name: "Dragon's Maze Promos", order: 349 },
  wmc: { count: 5, name: "World Magic Cup Qualifiers", order: 348 },
  ddk: { count: 80, name: "Duel Decks: Sorin vs. Tibalt", order: 347 },
  tddk: { count: 1, name: "Duel Decks: Sorin vs. Tibalt Tokens", order: 346 },
  gtc: { count: 249, name: "Gatecrash", order: 345 },
  tgtc: { count: 8, name: "Gatecrash Tokens", order: 344 },
  pgtc: { count: 10, name: "Gatecrash Promos", order: 343 },
  pdp14: {
    count: 3,
    name: "Duels of the Planeswalkers 2014 Promos ",
    order: 342,
  },
  l13: { count: 4, name: "League Tokens 2013", order: 341 },
  f13: { count: 12, name: "Friday Night Magic 2013", order: 340 },
  j13: { count: 9, name: "Judge Gift Cards 2013", order: 339 },
  ocm1: { count: 10, name: "Commander's Arsenal Oversized", order: 338 },
  cm1: { count: 18, name: "Commander's Arsenal", order: 337 },
  rtr: { count: 274, name: "Return to Ravnica", order: 336 },
  prtr: { count: 10, name: "Return to Ravnica Promos", order: 335 },
  trtr: { count: 12, name: "Return to Ravnica Tokens", order: 334 },
  tddj: { count: 1, name: "Duel Decks: Izzet vs. Golgari Tokens", order: 333 },
  ddj: { count: 90, name: "Duel Decks: Izzet vs. Golgari", order: 332 },
  v12: { count: 15, name: "From the Vault: Realms", order: 331 },
  tm13: { count: 11, name: "Magic 2013 Tokens", order: 330 },
  m13: { count: 249, name: "Magic 2013", order: 329 },
  pm13: { count: 6, name: "Magic 2013 Promos", order: 328 },
  opc2: { count: 40, name: "Planechase 2012 Planes", order: 327 },
  pc2: { count: 156, name: "Planechase 2012", order: 326 },
  tavr: { count: 8, name: "Avacyn Restored Tokens", order: 325 },
  avr: { count: 244, name: "Avacyn Restored", order: 324 },
  phel: { count: 6, name: "Open the Helvault", order: 323 },
  pavr: { count: 6, name: "Avacyn Restored Promos", order: 322 },
  ddi: { count: 77, name: "Duel Decks: Venser vs. Koth", order: 321 },
  tddi: { count: 2, name: "Duel Decks: Venser vs. Koth Tokens", order: 320 },
  tdka: { count: 4, name: "Dark Ascension Tokens", order: 319 },
  dka: { count: 158, name: "Dark Ascension", order: 318 },
  pdka: { count: 5, name: "Dark Ascension Promos", order: 317 },
  pw12: { count: 3, name: "Wizards Play Network 2012", order: 316 },
  pdp13: {
    count: 3,
    name: "Duels of the Planeswalkers 2013 Promos ",
    order: 315,
  },
  pidw: { count: 17, name: "IDW Comics Inserts", order: 314 },
  l12: { count: 2, name: "League Tokens 2012", order: 313 },
  j12: { count: 9, name: "Judge Gift Cards 2012", order: 312 },
  f12: { count: 13, name: "Friday Night Magic 2012", order: 311 },
  pd3: { count: 30, name: "Premium Deck Series: Graveborn", order: 310 },
  isd: { count: 264, name: "Innistrad", order: 309 },
  tisd: { count: 13, name: "Innistrad Tokens", order: 308 },
  pisd: { count: 5, name: "Innistrad Promos", order: 307 },
  tddh: {
    count: 2,
    name: "Duel Decks: Ajani vs. Nicol Bolas Tokens",
    order: 306,
  },
  ddh: { count: 80, name: "Duel Decks: Ajani vs. Nicol Bolas", order: 305 },
  v11: { count: 15, name: "From the Vault: Legends", order: 304 },
  tm12: { count: 7, name: "Magic 2012 Tokens", order: 303 },
  m12: { count: 249, name: "Magic 2012", order: 302 },
  pm12: { count: 3, name: "Magic 2012 Promos", order: 301 },
  ocmd: { count: 15, name: "Commander 2011 Oversized", order: 300 },
  cmd: { count: 318, name: "Commander 2011", order: 299 },
  pcmd: { count: 5, name: "Commander 2011 Launch Party", order: 298 },
  td2: {
    count: 88,
    name: "Duel Decks: Mirrodin Pure vs. New Phyrexia",
    order: 297,
  },
  nph: { count: 175, name: "New Phyrexia", order: 296 },
  tnph: { count: 5, name: "New Phyrexia Tokens", order: 295 },
  pnph: { count: 4, name: "New Phyrexia Promos", order: 294 },
  tddg: {
    count: 1,
    name: "Duel Decks: Knights vs. Dragons Tokens",
    order: 293,
  },
  ddg: { count: 81, name: "Duel Decks: Knights vs. Dragons", order: 292 },
  mbs: { count: 155, name: "Mirrodin Besieged", order: 291 },
  tmbs: { count: 6, name: "Mirrodin Besieged Tokens", order: 290 },
  pmbs: { count: 4, name: "Mirrodin Besieged Promos", order: 289 },
  me4: { count: 269, name: "Masters Edition IV", order: 288 },
  pmps11: { count: 5, name: "Magic Premiere Shop 2011", order: 287 },
  pdp12: {
    count: 3,
    name: "Duels of the Planeswalkers 2012 Promos ",
    order: 286,
  },
  pw11: { count: 3, name: "Wizards Play Network 2011", order: 285 },
  g11: { count: 8, name: "Judge Gift Cards 2011", order: 284 },
  p11: { count: 7, name: "Magic Player Rewards 2011", order: 283 },
  olgc: { count: 27, name: "Legacy Championship", order: 282 },
  f11: { count: 12, name: "Friday Night Magic 2011", order: 281 },
  ps11: { count: 224, name: "Salvat 2011", order: 280 },
  pd2: {
    count: 34,
    name: "Premium Deck Series: Fire and Lightning",
    order: 279,
  },
  td0: { count: 197, name: "Magic Online Theme Decks", order: 278 },
  som: { count: 249, name: "Scars of Mirrodin", order: 277 },
  tsom: { count: 10, name: "Scars of Mirrodin Tokens", order: 276 },
  psom: { count: 4, name: "Scars of Mirrodin Promos", order: 275 },
  ddf: { count: 79, name: "Duel Decks: Elspeth vs. Tezzeret", order: 274 },
  tddf: {
    count: 1,
    name: "Duel Decks: Elspeth vs. Tezzeret Tokens",
    order: 273,
  },
  v10: { count: 15, name: "From the Vault: Relics", order: 272 },
  tm11: { count: 6, name: "Magic 2011 Tokens", order: 271 },
  m11: { count: 249, name: "Magic 2011", order: 270 },
  pm11: { count: 6, name: "Magic 2011 Promos", order: 269 },
  oarc: { count: 45, name: "Archenemy Schemes", order: 268 },
  arc: { count: 150, name: "Archenemy", order: 267 },
  dpa: { count: 113, name: "Duels of the Planeswalkers", order: 266 },
  proe: { count: 4, name: "Rise of the Eldrazi Promos", order: 265 },
  troe: { count: 7, name: "Rise of the Eldrazi Tokens", order: 264 },
  roe: { count: 248, name: "Rise of the Eldrazi", order: 263 },
  dde: {
    count: 71,
    name: "Duel Decks: Phyrexia vs. the Coalition",
    order: 262,
  },
  tdde: {
    count: 3,
    name: "Duel Decks: Phyrexia vs. the Coalition Tokens",
    order: 261,
  },
  pwwk: { count: 6, name: "Worldwake Promos", order: 260 },
  twwk: { count: 6, name: "Worldwake Tokens", order: 259 },
  wwk: { count: 145, name: "Worldwake", order: 258 },
  pdp10: {
    count: 2,
    name: "Duels of the Planeswalkers 2010 Promos ",
    order: 257,
  },
  pmps10: { count: 5, name: "Magic Premiere Shop 2010", order: 256 },
  f10: { count: 12, name: "Friday Night Magic 2010", order: 255 },
  g10: { count: 8, name: "Judge Gift Cards 2010", order: 254 },
  p10: { count: 13, name: "Magic Player Rewards 2010", order: 253 },
  h09: { count: 41, name: "Premium Deck Series: Slivers", order: 252 },
  ddd: { count: 63, name: "Duel Decks: Garruk vs. Liliana", order: 251 },
  tddd: { count: 3, name: "Duel Decks: Garruk vs. Liliana Tokens", order: 250 },
  pzen: { count: 5, name: "Zendikar Promos", order: 249 },
  tzen: { count: 11, name: "Zendikar Tokens", order: 248 },
  zen: { count: 269, name: "Zendikar", order: 247 },
  me3: { count: 230, name: "Masters Edition III", order: 246 },
  ohop: { count: 40, name: "Planechase Planes", order: 245 },
  hop: { count: 169, name: "Planechase", order: 244 },
  phop: { count: 2, name: "Planechase Promos", order: 243 },
  v09: { count: 15, name: "From the Vault: Exiled", order: 242 },
  m10: { count: 249, name: "Magic 2010", order: 241 },
  tm10: { count: 8, name: "Magic 2010 Tokens", order: 240 },
  pm10: { count: 3, name: "Magic 2010 Promos", order: 239 },
  parb: { count: 3, name: "Alara Reborn Promos", order: 238 },
  arb: { count: 145, name: "Alara Reborn", order: 237 },
  tarb: { count: 4, name: "Alara Reborn Tokens", order: 236 },
  tddc: { count: 3, name: "Duel Decks: Divine vs. Demonic Tokens", order: 235 },
  ddc: { count: 62, name: "Duel Decks: Divine vs. Demonic", order: 234 },
  purl: { count: 10, name: "URL/Convention Promos", order: 233 },
  pcon: { count: 2, name: "Conflux Promos", order: 232 },
  tcon: { count: 2, name: "Conflux Tokens", order: 231 },
  con: { count: 145, name: "Conflux", order: 230 },
  pbook: { count: 0, name: "Miscellaneous Book Promos", order: 229 },
  pdtp: {
    count: 1,
    name: "Duels of the Planeswalkers 2009 Promos ",
    order: 228,
  },
  pmps09: { count: 5, name: "Magic Premiere Shop 2009", order: 227 },
  p09: { count: 13, name: "Magic Player Rewards 2009", order: 226 },
  f09: { count: 12, name: "Friday Night Magic 2009", order: 225 },
  g09: { count: 10, name: "Judge Gift Cards 2009", order: 224 },
  dd2: { count: 64, name: "Duel Decks: Jace vs. Chandra", order: 223 },
  tdd2: { count: 1, name: "Duel Decks: Jace vs. Chandra Tokens", order: 222 },
  pala: { count: 2, name: "Shards of Alara Promos", order: 221 },
  tala: { count: 10, name: "Shards of Alara Tokens", order: 220 },
  ala: { count: 250, name: "Shards of Alara", order: 219 },
  me2: { count: 245, name: "Masters Edition II", order: 218 },
  drb: { count: 15, name: "From the Vault: Dragons", order: 217 },
  peve: { count: 2, name: "Eventide Promos", order: 216 },
  teve: { count: 7, name: "Eventide Tokens", order: 215 },
  eve: { count: 180, name: "Eventide", order: 214 },
  pshm: { count: 2, name: "Shadowmoor Promos", order: 213 },
  shm: { count: 302, name: "Shadowmoor", order: 212 },
  tshm: { count: 12, name: "Shadowmoor Tokens", order: 211 },
  p15a: { count: 2, name: "15th Anniversary Cards", order: 210 },
  pmor: { count: 2, name: "Morningtide Promos", order: 209 },
  tmor: { count: 3, name: "Morningtide Tokens", order: 208 },
  mor: { count: 150, name: "Morningtide", order: 207 },
  pmps08: { count: 6, name: "Magic Premiere Shop 2008", order: 206 },
  p08: { count: 7, name: "Magic Player Rewards 2008", order: 205 },
  f08: { count: 12, name: "Friday Night Magic 2008", order: 204 },
  g08: { count: 5, name: "Judge Gift Cards 2008", order: 203 },
  dd1: { count: 62, name: "Duel Decks: Elves vs. Goblins", order: 202 },
  tdd1: { count: 3, name: "Duel Decks: Elves vs. Goblins Tokens", order: 201 },
  plrw: { count: 3, name: "Lorwyn Promos", order: 200 },
  lrw: { count: 301, name: "Lorwyn", order: 199 },
  tlrw: { count: 11, name: "Lorwyn Tokens", order: 198 },
  me1: { count: 195, name: "Masters Edition", order: 197 },
  "10e": { count: 510, name: "Tenth Edition", order: 196 },
  p10e: { count: 3, name: "Tenth Edition Promos", order: 195 },
  t10e: { count: 6, name: "Tenth Edition Tokens", order: 194 },
  pfut: { count: 2, name: "Future Sight Promos", order: 193 },
  fut: { count: 180, name: "Future Sight", order: 192 },
  pgpx: { count: 20, name: "Grand Prix Promos", order: 191 },
  ppro: { count: 15, name: "Pro Tour Promos", order: 190 },
  pplc: { count: 2, name: "Planar Chaos Promos", order: 189 },
  plc: { count: 165, name: "Planar Chaos", order: 188 },
  pres: { count: 0, name: "Resale Promos", order: 187 },
  pmps07: { count: 5, name: "Magic Premiere Shop 2007", order: 186 },
  g07: { count: 5, name: "Judge Gift Cards 2007", order: 185 },
  f07: { count: 12, name: "Friday Night Magic 2007", order: 184 },
  p07: { count: 7, name: "Magic Player Rewards 2007", order: 183 },
  hho: { count: 22, name: "Happy Holidays", order: 182 },
  ptsp: { count: 3, name: "Time Spiral Promos", order: 181 },
  tsp: { count: 301, name: "Time Spiral", order: 180 },
  tsb: { count: 121, name: "Time Spiral Timeshifted", order: 179 },
  pcsp: { count: 2, name: "Coldsnap Promos", order: 178 },
  cst: { count: 62, name: "Coldsnap Theme Decks", order: 177 },
  csp: { count: 155, name: "Coldsnap", order: 176 },
  pdis: { count: 2, name: "Dissension Promos", order: 175 },
  dis: { count: 180, name: "Dissension", order: 174 },
  pcmp: { count: 12, name: "Champs and States", order: 173 },
  pgpt: { count: 2, name: "Guildpact Promos", order: 172 },
  gpt: { count: 167, name: "Guildpact", order: 171 },
  pal06: { count: 9, name: "Arena League 2006", order: 170 },
  pmps06: { count: 5, name: "Magic Premiere Shop 2006", order: 169 },
  pjas: { count: 6, name: "Junior APAC Series", order: 168 },
  f06: { count: 12, name: "Friday Night Magic 2006", order: 167 },
  phuk: { count: 60, name: "Hachette UK", order: 166 },
  pdci: { count: 80, name: "DCI Promos", order: 165 },
  p06: { count: 7, name: "Magic Player Rewards 2006", order: 164 },
  g06: { count: 4, name: "Judge Gift Cards 2006", order: 163 },
  p2hg: { count: 1, name: "Two-Headed Giant Tournament", order: 162 },
  prav: { count: 2, name: "Ravnica: City of Guilds Promos", order: 161 },
  rav: { count: 306, name: "Ravnica: City of Guilds", order: 160 },
  psal: { count: 720, name: "Salvat 2005", order: 159 },
  p9ed: { count: 2, name: "Ninth Edition Promos", order: 158 },
  "9ed": { count: 710, name: "Ninth Edition", order: 157 },
  psok: { count: 2, name: "Saviors of Kamigawa Promos", order: 156 },
  sok: { count: 165, name: "Saviors of Kamigawa", order: 155 },
  pbok: { count: 2, name: "Betrayers of Kamigawa Promos", order: 154 },
  bok: { count: 165, name: "Betrayers of Kamigawa", order: 153 },
  pmps: { count: 20, name: "Magic Premiere Shop 2005", order: 152 },
  pal05: { count: 8, name: "Arena League 2005", order: 151 },
  pjse: { count: 8, name: "Junior Series Europe", order: 150 },
  f05: { count: 12, name: "Friday Night Magic 2005", order: 149 },
  g05: { count: 4, name: "Judge Gift Cards 2005", order: 148 },
  p05: { count: 6, name: "Magic Player Rewards 2005", order: 147 },
  punh: { count: 1, name: "Unhinged Promos", order: 146 },
  unh: { count: 168, name: "Unhinged", order: 145 },
  pchk: { count: 1, name: "Champions of Kamigawa Promos", order: 144 },
  chk: { count: 307, name: "Champions of Kamigawa", order: 143 },
  wc04: { count: 103, name: "World Championship Decks 2004", order: 142 },
  pmrd: { count: 1, name: "Mirrodin Promos", order: 141 },
  p5dn: { count: 1, name: "Fifth Dawn Promos", order: 140 },
  "5dn": { count: 165, name: "Fifth Dawn", order: 139 },
  pdst: { count: 1, name: "Darksteel Promos", order: 138 },
  dst: { count: 165, name: "Darksteel", order: 137 },
  pal04: { count: 14, name: "Arena League 2004", order: 136 },
  p04: { count: 6, name: "Magic Player Rewards 2004", order: 135 },
  g04: { count: 6, name: "Judge Gift Cards 2004", order: 134 },
  f04: { count: 12, name: "Friday Night Magic 2004", order: 133 },
  mrd: { count: 306, name: "Mirrodin", order: 132 },
  wc03: { count: 142, name: "World Championship Decks 2003", order: 131 },
  p8ed: { count: 1, name: "Eighth Edition Promos", order: 130 },
  "8ed": { count: 711, name: "Eighth Edition", order: 129 },
  pscg: { count: 1, name: "Scourge Promos", order: 128 },
  scg: { count: 143, name: "Scourge", order: 127 },
  plgn: { count: 1, name: "Legions Promos", order: 126 },
  lgn: { count: 145, name: "Legions", order: 125 },
  pmoa: { count: 85, name: "Magic Online Avatars", order: 124 },
  pjjt: { count: 12, name: "Japan Junior Tournament", order: 123 },
  pal03: { count: 8, name: "Arena League 2003", order: 122 },
  ovnt: { count: 35, name: "Vintage Championship", order: 121 },
  p03: { count: 7, name: "Magic Player Rewards 2003", order: 120 },
  f03: { count: 13, name: "Friday Night Magic 2003", order: 119 },
  g03: { count: 3, name: "Judge Gift Cards 2003", order: 118 },
  ons: { count: 351, name: "Onslaught", order: 117 },
  pons: { count: 1, name: "Onslaught Promos", order: 116 },
  wc02: { count: 153, name: "World Championship Decks 2002", order: 115 },
  phj: { count: 5, name: "Hobby Japan Promos", order: 114 },
  prm: { count: 3110, name: "Magic Online Promos", order: 113 },
  pjud: { count: 1, name: "Judgment Promos", order: 112 },
  jud: { count: 143, name: "Judgment", order: 111 },
  ptor: { count: 3, name: "Torment Promos", order: 110 },
  tor: { count: 143, name: "Torment", order: 109 },
  pal02: { count: 5, name: "Arena League 2002", order: 108 },
  pr2: { count: 6, name: "Magic Player Rewards 2002", order: 107 },
  g02: { count: 2, name: "Judge Gift Cards 2002", order: 106 },
  f02: { count: 12, name: "Friday Night Magic 2002", order: 105 },
  dkm: { count: 58, name: "Deckmasters", order: 104 },
  pody: { count: 1, name: "Odyssey Promos", order: 103 },
  ody: { count: 353, name: "Odyssey", order: 102 },
  wc01: { count: 138, name: "World Championship Decks 2001", order: 101 },
  psdg: { count: 10, name: "Sega Dreamcast Cards", order: 100 },
  papc: { count: 1, name: "Apocalypse Promos", order: 99 },
  apc: { count: 143, name: "Apocalypse", order: 98 },
  "7ed": { count: 708, name: "Seventh Edition", order: 97 },
  ppls: { count: 1, name: "Planeshift Promos", order: 96 },
  pls: { count: 146, name: "Planeshift", order: 95 },
  pal01: { count: 12, name: "Arena League 2001", order: 94 },
  g01: { count: 2, name: "Judge Gift Cards 2001", order: 93 },
  mpr: { count: 8, name: "Magic Player Rewards 2001", order: 92 },
  f01: { count: 7, name: "Friday Night Magic 2001", order: 91 },
  pinv: { count: 1, name: "Invasion Promos", order: 90 },
  inv: { count: 353, name: "Invasion", order: 89 },
  btd: { count: 90, name: "Beatdown Box Set", order: 88 },
  wc00: { count: 117, name: "World Championship Decks 2000", order: 87 },
  ppcy: { count: 1, name: "Prophecy Promos", order: 86 },
  pcy: { count: 144, name: "Prophecy", order: 85 },
  s00: { count: 20, name: "Starter 2000", order: 84 },
  pnem: { count: 1, name: "Nemesis Promos", order: 83 },
  nem: { count: 143, name: "Nemesis", order: 82 },
  pelp: { count: 15, name: "European Land Program", order: 81 },
  pal00: { count: 11, name: "Arena League 2000", order: 80 },
  fnm: { count: 11, name: "Friday Night Magic 2000", order: 79 },
  g00: { count: 2, name: "Judge Gift Cards 2000", order: 78 },
  psus: { count: 18, name: "Junior Super Series", order: 77 },
  brb: { count: 136, name: "Battle Royale Box Set", order: 76 },
  pmmq: { count: 1, name: "Mercadian Masques Promos", order: 75 },
  mmq: { count: 350, name: "Mercadian Masques", order: 74 },
  pwos: { count: 1, name: "Wizards of the Coast Online Store", order: 73 },
  pwor: { count: 2, name: "World Championship Promos", order: 72 },
  wc99: { count: 111, name: "World Championship Decks 1999", order: 71 },
  pgru: { count: 5, name: "Guru", order: 70 },
  s99: { count: 173, name: "Starter 1999", order: 69 },
  puds: { count: 1, name: "Urza's Destiny Promos", order: 68 },
  uds: { count: 143, name: "Urza's Destiny", order: 67 },
  pptk: { count: 2, name: "Portal: Three Kingdoms Promos", order: 66 },
  ptk: { count: 180, name: "Portal Three Kingdoms", order: 65 },
  "6ed": { count: 351, name: "Classic Sixth Edition", order: 64 },
  pulg: { count: 2, name: "Urza's Legacy Promos", order: 63 },
  ulg: { count: 143, name: "Urza's Legacy", order: 62 },
  pal99: { count: 10, name: "Arena League 1999", order: 61 },
  g99: { count: 1, name: "Judge Gift Cards 1999", order: 60 },
  ath: { count: 85, name: "Anthologies", order: 59 },
  pusg: { count: 1, name: "Urza's Saga Promos", order: 58 },
  usg: { count: 356, name: "Urza's Saga", order: 57 },
  palp: { count: 15, name: "Asia Pacific Land Program", order: 56 },
  wc98: { count: 117, name: "World Championship Decks 1998", order: 55 },
  tugl: { count: 6, name: "Unglued Tokens", order: 54 },
  ugl: { count: 88, name: "Unglued", order: 53 },
  p02: { count: 165, name: "Portal Second Age", order: 52 },
  pexo: { count: 1, name: "Exodus Promos", order: 51 },
  exo: { count: 143, name: "Exodus", order: 50 },
  psth: { count: 1, name: "Stronghold Promos", order: 49 },
  sth: { count: 143, name: "Stronghold", order: 48 },
  jgp: { count: 3, name: "Judge Gift Cards 1998", order: 47 },
  ptmp: { count: 1, name: "Tempest Promos", order: 46 },
  tmp: { count: 350, name: "Tempest", order: 45 },
  wc97: { count: 131, name: "World Championship Decks 1997", order: 44 },
  wth: { count: 167, name: "Weatherlight", order: 43 },
  olep: { count: 83, name: "Oversized League Prizes", order: 42 },
  por: { count: 257, name: "Portal", order: 41 },
  pvan: { count: 32, name: "Vanguard Series", order: 40 },
  pmic: { count: 1, name: "MicroProse Promos", order: 39 },
  past: { count: 12, name: "Astral Cards", order: 38 },
  "5ed": { count: 460, name: "Fifth Edition", order: 37 },
  vis: { count: 167, name: "Visions", order: 36 },
  itp: { count: 67, name: "Introductory Two-Player Set", order: 35 },
  mgb: { count: 10, name: "Multiverse Gift Box", order: 34 },
  mir: { count: 353, name: "Mirage", order: 33 },
  pred: { count: 1, name: "Redemption Program", order: 32 },
  pcel: { count: 9, name: "Celebration Cards", order: 31 },
  parl: { count: 7, name: "Arena League 1996", order: 30 },
  rqs: { count: 65, name: "Rivals Quick Start Set", order: 29 },
  plgm: { count: 2, name: "DCI Legend Membership", order: 28 },
  all: { count: 199, name: "Alliances", order: 27 },
  ptc: { count: 308, name: "Pro Tour Collector Set", order: 26 },
  o90p: { count: 10, name: "Oversized 90's Promos", order: 25 },
  hml: { count: 140, name: "Homelands", order: 24 },
  rin: { count: 69, name: "Rinascimento", order: 23 },
  ren: { count: 122, name: "Renaissance", order: 22 },
  chr: { count: 125, name: "Chronicles", order: 21 },
  bchr: { count: 125, name: "Chronicles Foreign Black Border", order: 20 },
  ice: { count: 383, name: "Ice Age", order: 19 },
  "4bb": { count: 378, name: "Fourth Edition Foreign Black Border", order: 18 },
  "4ed": { count: 379, name: "Fourth Edition", order: 17 },
  pmei: { count: 62, name: "Media and Collaboration Promos", order: 16 },
  fem: { count: 187, name: "Fallen Empires", order: 15 },
  phpr: { count: 5, name: "HarperPrism Book Promos", order: 14 },
  drk: { count: 122, name: "The Dark", order: 13 },
  pdrc: { count: 1, name: "Dragon Con", order: 12 },
  sum: { count: 306, name: "Summer Magic / Edgar", order: 11 },
  leg: { count: 310, name: "Legends", order: 10 },
  "3ed": { count: 306, name: "Revised Edition", order: 9 },
  fbb: { count: 307, name: "Foreign Black Border", order: 8 },
  atq: { count: 102, name: "Antiquities", order: 7 },
  arn: { count: 92, name: "Arabian Nights", order: 6 },
  cei: { count: 302, name: "Intl. Collectors' Edition", order: 5 },
  ced: { count: 302, name: "Collectors' Edition", order: 4 },
  "2ed": { count: 302, name: "Unlimited Edition", order: 3 },
  leb: { count: 302, name: "Limited Edition Beta", order: 2 },
  lea: { count: 295, name: "Limited Edition Alpha", order: 1 },
};

export const userNames = {
  "152135173813698561": "Ben",
  "135410033524604928": "Yems",
  194831804329492480: "Oli",
  "312274225144791052": "Dan",
  "307938372943478785": "Ollie",
  "203238971009007616": "Tom",
};
